### ISSUE TITLE
SIGSEGV in selinux_setup() (rc-selinux.c:337)

### ISSUE THREAD

**Issue by konsolebox** [OpenRC/openrc#104]
I'm getting a SIGSEGV in this line:

`curr_t = xstrdup(context_type_get(curr_con));`

The cause is that, `context_new()` in `curr_con = context_new(curr_context);` returns 0 when `curr_context`'s value is "invalid" for the function.  This is the part in libselinux (2.6) where it gets rejected (`context.c:35`):

	if (count < 2 || count > 5) {	/* might not have a range */
		goto err;
	}

The "invalid" value I'm having is "kernel", which as I examined was read from `/proc/thread-self/attr/current` by `getcon()'s subfunctions` (see `procattr.c:79` of libselinux 2.6). I still have to examine why I'm having this value. I have some idea why but I think it's not yet necessary to mention it here.

But regardless of that, I think OpenRC should add some sanity checks for this to prevent SIGSEGV from happening (basically, `if (curr_context == NULL) ... errno ...`), and perhaps add some messages so users would get an idea of what's going on.  Also, if "kernel" is a valid context, perhaps it should also do something about it, regardless of whether it's caused by a wrong configuration or not.

**Comment by perfinion** [comment]
hmm i got reports of people hitting something similar in portage. I'll add these checks and check upstream why this changed. It used to return something else but i cant remember what.

**Comment by konsolebox** [comment]
I'm still having "kernel" in `/proc/thread-self/attr/current`, but I'm already able to make a proper boot with this patch:

```
--- openrc-9999/src/rc/rc-selinux.c.orig	2016-11-16 07:10:12.497066160 +0000
+++ openrc-9999/src/rc/rc-selinux.c	2016-11-16 07:10:18.587066569 +0000
@@ -334,6 +334,10 @@
 
 	/* extract the type from the context */
 	curr_con = context_new(curr_context);
+	if (curr_con == NULL) {
+		free(curr_context);
+		goto out;
+	}
 	curr_t = xstrdup(context_type_get(curr_con));
 	/* dont need them anymore so free() now */
 	context_free(curr_con);
```

**Comment by konsolebox** [comment]
I think the patch is good but it would be nice to add a warning, like this warning message from portage:

`/usr/lib64/python2.7/site-packages/portage/_selinux.py:81: UserWarning: Invalid SELinux context: kernel`

**Comment by konsolebox** [comment]
Btw, the cause of this issue was because for some reason I wasn't able to reinstall sys-apps/sysvinit with the selinux flag after a world update.  Please consider changing `>=sys-apps/sysvinit-2.86-r6` to `>=sys-apps/sysvinit-2.86-r6[selinux?]` in the RDEPEND section of the ebuild.

**Comment by perfinion** [comment]
@konsolebox Just pushed this to the git repo
