### ISSUE TITLE
Don't ignore initscripts with different shebang silently

### ISSUE THREAD

**Issue by robotanarchy** [OpenRC/openrc#120]
Hello OpenRC devs,

I'm using OpenRC on Parabola Linux.
After the upgrade from 0.24 to 0.24.1 I have noticed, that *some* init scripts just did not get executed during boot anymore. But they worked fine with `rc-service $service start`.
I have debugged this issue for about two hours now, and found the solution by reading a random open [issue](https://github.com/OpenRC/openrc/issues/119#issuecomment-286911335): **Initscripts without the correct shebang (`#!/sbin/openrc-run` on Parabola) get ignored.**

Lots of initscripts on Parabola still have `#!/usr/bin/openrc-run` as shebang, and of course my custom init scripts had that shebang too (as I have copied old Parabola init scripts as starting point).

I want to spare other people the same pain, so could you please not silently ignore those initscripts, but display a waning when encountering these (eg. during init)?

Thanks for making OpenRC!

EDIT: Parabola Bugreport: https://labs.parabola.nu/issues/1240

**Comment by williamh** [comment]
This is actually on my radar, I just haven't gotten to it yet. The shebang must end with openrc-run, but I am going to look into a way just to check that and not worry about the path.
