### ISSUE TITLE
agetty login display

### ISSUE THREAD

**Issue by cromerc** [OpenRC/openrc#121]
I just converted to using agetty in openrc instead of sysvinit's inittab. However there is a visual issue with the agetty login display when run from openrc. What happens is the login prompt is shown in the middle of other text instead of at the end. To get around this I put --delay in my /etc/conf.d/agetty file like so:
`agetty_options="--noclear --delay 1"`

This does fix the graphical issue of the text overlapping, but introduces a delay every time that I logout of my session.

Is there a better way to fix this without using --delay?

**Comment by williamh** [comment]
I'm closing this, only because I don't know of a better way to fix it than what you are doing. If someone does, or if someone thinks OpenRC should do something different with this by default, please feel free to comment or open another issue.

**Comment by cromerc** [comment]
Another solution would be to create an agetty runlevel that is called after default, and when it is called, use the --quiet argument so that the agetty runlevel doesn't show anything on the screen. This solution would require modifiying the openrc-init to detect and run an agetty runlevel if it exists.
