### ISSUE TITLE
init.d/bootmisc with openrc-init

### ISSUE THREAD

**Issue by cromerc** [OpenRC/openrc#124]
I switched over to openrc-init and ran into this after issuing the command "openrc-shutdown --reboot":

`/etc/openrc/init.d/bootmisc: line 243: halt: command not found`

Obviously this error occurs because I uninstalled sysvinit after verifying that openrc-init works.

**Comment by cromerc** [comment]
Just noticed that there are some other errors, I didn't really notice at first since they are not in my rc.log, my computer is too fast and I had to take a quick photo during shutdown just to be able to read these:
`etc/openrc/init.d/killprocs: line 22: killall5: command not found`

**Comment by williamh** [comment]
For multiple reasons, you can't uninstall sysvinit at this point. I am planning on looking into a way to be sysvinit compatible.
