### ISSUE TITLE
Supervise-daemon does not give up restarting a daemon if the daemon fails to start

### ISSUE THREAD

**Issue by haarts** [OpenRC/openrc#126]
I'm creating a OpenRC service file and I'm utilizing supervise-daemon. The 'thing' I want to supervise is a simple shell script.
When starting the service with `rc-service transcoder start` if ends up in an infinite loop spewing `supervise-daemon: failed to exec `/home/transcoder/fetch.sh': No such file or directory`
I've checked and double checked if the file exists and it does, it is also executable.
Does openrc use some sort of implicit chroot?

My service file:
```
#!/sbin/openrc-run
supervisor=supervise-daemon

user=transcoder
supervise_daemon_args="-u $user"
command=/home/transcoder/fetch.sh
command_args="arg1 arg2"
pidfile=/run/transcoder.pid
retry=10800 # 3 hours
transcoder_status_file=/run/transcoder_has_ever_been_started

depend() {
    need net
}

start_pre() {
  # If this file exists then transcoder has been started before.
  # It might be so that the media server is down. Wait for 3 hours.
  if [ -f $transcoder_status_file ]; then
    sleep $retry
  fi

  touch /run/transcoder_has_ever_been_started
}
```

Based on the source I've more of less recreated the explicit supervise-daemon command:
```
supervise-daemon --start --pidfile /run/transcoder.pid /home/transcoder/fetch.sh -- arg1 arg2
```

But that yields the same result:
```
 * supervise-daemon: failed to exec `/home/transcoder/fetch.sh': No such file or directory
 * supervise-daemon: failed to exec `/home/transcoder/fetch.sh': No such file or directory
 * supervise-daemon: failed to exec `/home/transcoder/fetch.sh': No such file or directory
 * supervise-daemon: failed to exec `/home/transcoder/fetch.sh': No such file or directory
 * supervise-daemon: failed to exec `/home/transcoder/fetch.sh': No such file or directory
 * supervise-daemon: failed to exec `/home/transcoder/fetch.sh': No such file or directory
 * supervise-daemon: failed to exec `/home/transcoder/fetch.sh': No such file or directory
 * supervise-daemon: failed to exec `/home/transcoder/fetch.sh': No such file or directory
 * supervise-daemon: failed to exec `/home/transcoder/fetch.sh': No such file or directory
```

**Comment by dwfreed** [comment]
What's the contents of /home/transcoder/fetch.sh ?

**Comment by haarts** [comment]
... I feel like quite the idiot. Some of the commands in `fetch.sh` are not installed. Like `ffmpeg`. 
Is there a way to propagate the error from the `fetch.sh` up?

BTW Is `start_pre()` used at all when using `supervise-daemon`?

**Comment by dwfreed** [comment]
The message suggests your script is missing a shebang line, which is why I wanted to see it.  So it's not even executing the script at all, so there'd be no way to know whether the commands in the script exist.

start_pre is used, but it is not called between restarting the daemon being monitored, only when the initscript itself is first started.

**Comment by haarts** [comment]
Thanks for clarifying the start_pre usage.

I just check regarding the shebang line. It's there, but it is using bash perhaps that's weird?

```
#!/bin/bash -e

cd "$(dirname "$0")"
source secrets.sh

while true; do
     <snip>
done
```

I've gotten somewhat further but starting and stopping is still flaky. With the `start_pre` I was hoping to implement some start delay. That seems to work but when the service is waiting in the `start_pre` function I don't get my prompt back when starting it and on an other shell I get:

```
dust:~# rc-service transcoder stop
 * ERROR: transcoder stopped by something else
dust:~# rc-status
Runlevel: default
 syslog                                                                                                                                                                                                 [  started  ]
 crond                                                                                                                                                                                                  [  started  ]
 acpid                                                                                                                                                                                                  [  started  ]
 sshd                                                                                                                                                                                                   [  started  ]
 chronyd                                                                                                                                                                                                [  started  ]
 transcoder                                                                                                                                                                                             [ starting  ]
 telegraf                                                                                                                                                                                               [  started  ]
Dynamic Runlevel: hotplugged
Dynamic Runlevel: needed/wanted
 sysfs                                                                                                                                                                                                  [  started  ]
 fsck                                                                                                                                                                                                   [  started  ]
 root                                                                                                                                                                                                   [  started  ]
 localmount                                                                                                                                                                                             [  started  ]
 klogd                                                                                                                                                                                                  [  started  ]
Dynamic Runlevel: manual
dust:~#
```

So I can't stop it.

**Comment by dwfreed** [comment]
Service start/stop takes place in serial (including during runlevel changing, except when rc_parallel=yes, but that's considered experimental and untested), so the sleep you have in start_pre will block openrc-run until it finishes.  I don't know why it gave you no such file or directory, because I made a simple test case with a script and a bad command, and it "worked" just fine, in that it repeatedly told me the bad command was not found.

**Comment by haarts** [comment]
I've reproduced it. This is the init.d script called `/etc/init.d/test` (chmod +x):

```
#!/sbin/openrc-run
supervisor=supervise-daemon

user=transcoder
supervise_daemon_args="-u $user"
command=/home/transcoder/test.sh
command_args="arg1 arg2"
pidfile=/run/test.pid

depend() {
    need net
}
```

This is the `/home/transcoder/test.sh` script:
```
#!/bin/zsh

echo 'hello'
```

I don't have Zsh installed and this does the infinite loop again.

**Comment by williamh** [comment]
The issue is, if a daemon fails to start, supervise-daemon always immediately tries to restart it, so this could end up in an infinite loop.
The idea of supervise-daemon is to restart a daemon when it crashes. Can we, or should we,  find some way to be "smart" and give up restarting the daemon?

**Comment by cromerc** [comment]
@williamh 
Maybe a configuration setting that allows the admin to choose a number of retries before giving up?

**Comment by vapier** [comment]
we should mirror something like upstart has: it has config options to control respawn, and how many times to retry within a time period.

http://upstart.ubuntu.com/cookbook/#respawn
http://upstart.ubuntu.com/cookbook/#respawn-limit

semi-related, it also has a config option for running an arbitrary command after a service has stopped, so you could insert a sleep there if the daemon wanted to.  i don't think it needs to be part of this though.

**Comment by williamh** [comment]
We don't need something like the "respawn" option you cited, because supervise-daemon should always respawn whatever it is supervising. However, I think respawn-limit will do what we want. I'm looking at adding a respawn-limit option that takes either "unlimited" or "count:period" as its argument.

**Comment by duanyao** [comment]
In my opinion, `--respawn-limit count:period` is useful for workstations, but maybe not for servers -- for the latter, I still want unlimited restarts, but with a period to reduce resource consumption. Maybe you could allow `--respawn-limit 0:period`? Additionally, the first restart should be immediate in spite of "period" to achieve lowest downtime in most cases.

**Comment by vapier** [comment]
we don't differentiate between "desktop" and "server".  and even then, respawn isn't a desktop specific concept.  if services get out of control on a server, you'd want to limit their damage.

**Comment by duanyao** [comment]
Just indefinitely restarting a failed service with 10s interval can hardly cause damage by itself, I guess?
Anyway, it's up to the admins to decided, and the supervisor should be flexible enough to allow it. According to upstart doc mentioned above, it does allow unlimited respawn along with limited interval.

Even if `--respawn-limit 0:10` is not supported, one can hack it with `--respawn-limit 10000000:10`, just not quite intuitive.

**Comment by vapier** [comment]
it depends entirely on the service.  a generalization like "it can never be a problem" doesn't really work.  but as i said, it doesn't matter, as the code will be there regardless.  server admins can choose to config things however they like.

**Comment by williamh** [comment]
I've been asked to split the respawn-limit option into two options -- a  max respawn count and a time period. These, along with a respawn-delay option will be coming in an update today.

**Comment by williamh** [comment]
This is in 0.26.2.
