### ISSUE TITLE
start-stop-daemon: add the ability to pipe stdout and/or stderr to a process rather than a file

### ISSUE THREAD

**Issue by williamh** [OpenRC/openrc#127]
I have been asked to consider adding options to start-stop-daemon which would allow stdout and/or stderr to be piped to a process rather than just redirected to a file.
The suggested command line options are --stderr-pipe "command" and --stdout-pipe "command".

**Comment by dwfreed** [comment]
They can just use named pipes :man_shrugging:

**Comment by williamh** [comment]
@chutzpah I'm adding you here.

**Comment by kmoore134** [comment]
This is something we'd be interested in testing for FreeBSD/TrueOS.

**Comment by heistp** [comment]
FWIW I'd like to see this. Services written in Go usually expect to write to stdout and rely on the init facility (often systemd) to send this to the syslog. I now have an OpenRC service script for [IRTT](https://github.com/heistp/irtt), but there's no easy way I can get it to log. I could add the ability for IRTT to use Go's log/syslog package, which I'll probably have to do to get this working soon, but having this ability in OpenRC would make things simpler.

**Comment by williamh** [comment]
This is available in OpenRC 0.37. The following commits are related to this feature:

a097933e
e6d01471
d4501a9f
ec8abea4
