### ISSUE TITLE
implement an openrc-specific version of killall5

### ISSUE THREAD

**Issue by williamh** [OpenRC/openrc#129]
If we can use our own version of killall5, this will remove our dependency on sysvinit.

**Comment by udeved** [comment]
It came in very handy, and sysvinit could be dropped.
My first tests with openrc-init on arch based system went not so well without sysvinit installed.

**Comment by cromerc** [comment]
What issues did you have running it under arch?

I have only tried the openrc-init under lfs and it worked fine.

**Comment by udeved** [comment]
@cromerc 

Its to do with the missig multicall binary for shutdown. Boot wet fine, but shutdown and process termination not so fine, despite compat symlinks
https://github.com/OpenRC/openrc/issues/128

**Comment by williamh** [comment]
This will also allow me to close http://bugs.gentoo.org/show_bug.cgi?id=376977
