### ISSUE TITLE
Mount efivars read-only

### ISSUE THREAD

**Issue by dakkar** [OpenRC/openrc#134]
Hello! 
`/etc/init.d/sysfs` mounts `efivars` with the same options as all the other `/sys/**` filesystems. This will usually result on it being mounted read-write.
But (as discussed in systemd/systemd#2402) this may not be the best choice.
Maybe [when mounting `efivarsfs`](https://github.com/OpenRC/openrc/blob/5f5b1f7cbefd0bc14352e86a9c33260266f98d9b/init.d/sysfs.in#L100-L104) we could specify `ro`.
What do you think?

**Comment by cromerc** [comment]
I second the change to "ro". I had an issue with systemd mouting efivars as rw while doing an install of Fedora. The fedora installer did something during install(even though I specified that I didn't want to install a bootloader......) that left my entire efi setup was completely erased leaving me with an unbootable system. It erased my arch linux, gentoo, and windows efi files...
Mounting it as rw by default is dangerous. It is better to remount as rw when something needs to be changed, then remount back to ro after the changes are done.

**Comment by superm1** [comment]
Mounting read only is causing problems with fwupdate and efibootmgr. See 
https://github.com/hughsie/fwupd/issues/625

Furthermore it's not necessary since the kernel makes efivarfs immutable.
torvalds/linux@ed8b0de

**Comment by cromerc** [comment]
@superm1 Considering that many distros are still shipping 3.x kernels still(Cent OS, Debian, Zentyal, RHEL, etc), it is still a necessary precaution in OpenRC to mount them RO by default. Making it an option in OpenRC that can be changed would make more sense.

**Comment by joakim-tjernlund** [comment]
yes, a config option / USE flag makes most sense.
