### ISSUE TITLE
supervise-daemon dies when started by /etc/rc at boot

### ISSUE THREAD

**Issue by kmoore134** [OpenRC/openrc#135]
I'm trying to get supervise-daemon working with some of our services here on TrueOS/FreeBSD. The services appear fine, and indeed work great when spun up manually. However we've noticed that services configured to use it at boot, the controlling supervise-daemon process either crashes or exits (I can't find evidence of a segfault) right after /etc/rc finishes up. The target program/daemon continues to live on and this gets us into a nice sideways state. 

As a super-ugly work-around, I found by starting supervise-daemon with "eval start-stop-daemon --start supervise-daemon -- <.....>" in libexec/rc/sh/supervise-daemon.sh fixes the issue. Why it fixes the issue? No idea, but the parent process of supervise-daemon then never dies, and everything appears to function normally.

(Avert your eyes children!) https://github.com/trueos/freebsd/commit/616ee4db1755ba8d4ee5c9d85f1e4231a0c2cb0e

**Comment by williamh** [comment]
Hi, can you check 0.31.2 and let me know if this is still happening?

**Comment by williamh** [comment]
Please test with 0.34.10 and let me know if the issue is resolved.

**Comment by williamh** [comment]
@kmoore134 Hi, please test with OpenRC 0.34.11 and let me know whether or not this issue is resolved.

Thanks,

William

**Comment by williamh** [comment]
I am closing this due to no response. However, please feel free to comment on the issue and if it is still an issue it can be re-opened.
Thanks much.

William
