### ISSUE TITLE
Integration of lsb2rcconf to OpenRC

### ISSUE THREAD

**Issue by xaionaro** [OpenRC/openrc#14]
Hello.

I just want to know, what do you think about integration of [lsb2rcconf](https://github.com/xaionaro/openrc-lsb) to OpenRC?

**Comment by vapier** [comment]
some more background for folks unfamiliar with this stuff:
https://wiki.debian.org/LSBInitScripts

i'm inclined to pass.  LSB adoption seems to be too low to bother.
