### ISSUE TITLE
LXDM/LXSession with openrc-shutdown

### ISSUE THREAD

**Issue by cromerc** [OpenRC/openrc#140]
In LXDM and LXSession the code calls the shutdown binary directly like this:
`shutdown -h now`
This fails with the sysvinit compat that openrc-shutdown provides since it is an invalid way to call openrc-shutdown.

**Comment by cromerc** [comment]
Looks like this is also a problem with consolekit. Consolekit also calls shutdown with "-h now" under linux and "-hp now" under openbsd bsd.

**Comment by udeved** [comment]
https://github.com/manjaro/packages-openrc/tree/master/openrc

@cromerc 

Can you please test with the patches?

https://github.com/OpenRC/openrc/issues/141

Works fie for me so far on plasma system.

**Comment by cromerc** [comment]
These patches won't fix this issue. The problem here is that openrc-shutdown does not accept the arguments "-h now". Temporarily I ended up patching consolekit and lxdm to call "poweroff" instead of "shutdown -h now" until a better solution is found.

**Comment by udeved** [comment]
I see, I use elogind since a while as default, annd that solves a lot of issues compared to ck.

**Comment by cromerc** [comment]
I decided to allow the users to decide between consolekit and elogind, so I have to try to keep it working for both types of installations. The big issue here is that consolekit, lxdm, and probably many other software depend on the shutdown command being called in a certain way(the sysvinit way) but the sysvinit compat provided by openrc can't handle it correctly yet.

**Comment by udeved** [comment]
The problem is the dependency of arch binary packages, they are simply made for systemd, and elogind eases the pain. ;)
I will give ck a shot again and relax conflicts once it supports multiseat, ie logind interface.
Still leaves the crazy systemd/libsystemd depend in the arch tree, and no way to get liblogid off the system to replace it with something else, because liblogind is part of libsystemd.

**Comment by cromerc** [comment]
Yep, I am tired of systemd creeping in under Arch Linux and complicating everything in it's binaries which are all compiled against systemd or with systemd as dependencies. Which is why I decided to start a new distro with OpenRC and Pacman based off Linux From Scratch. I figure the best way to avoid systemd is with a distro completely devoid of it from the start. It is still in the early stages of development and I just recently finished getting Xorg and LXDE up and running.

**Comment by udeved** [comment]
Yes, and that's the reason I switched to elogind, packages that don't have a direct systemd package depend work with elogind. You spare yourself with patching lots of DE stuff for ck, and can focus eliminating the direct systemd depends for at least the core repo.

**Comment by williamh** [comment]
I think the issue you are hitting is openrc-shutdown uses -h for help instead of hault, correct? The provided sysv-compatible shutdown is just a script, so I may be able to remap -h to --halt there. I'll look at it this weekend.

**Comment by cromerc** [comment]
@williamh 
Correct, the issue is that it is mapped to help. I do believe remapping -h to --halt will solve this.

**Comment by williamh** [comment]
rebuilding arguments isn't quite correct yet.
