### ISSUE TITLE
poweroff fails in sysvinit mode

### ISSUE THREAD

**Issue by udeved** [OpenRC/openrc#146]
This one is hard to log.
openrc-0.27.2 doesn't poweroff, in my case shutdown from plasma with elogind running.

The last message states something

`system halted (reboot)`

as if the wrong signal is sent, but apparently the system doesn't reboot, remains stuck, and manual poweroff button is the only way.

**Comment by cromerc** [comment]
I did some review of elogind, when poweroff/shutdown is pressed it calls halt using parameters that the halt in the sysvinit compat does not support. I believe the same patching is needed for halt that was done for shutdown and poweroff to correct the issue.

**Comment by williamh** [comment]
What parameters do I need to support in halt?

**Comment by cromerc** [comment]
Not sure which specific ones at the moment. I will look into which parameters it calls on the weekend.

**Comment by williamh** [comment]
@cromerc Do you have any updates on this?  Thanks. :-)

**Comment by udeved** [comment]
@williamh 


https://github.com/elogind/elogind/blob/v229-stable/src/login/loginctl.c

I think this would be of use.

**Comment by cromerc** [comment]
@williamh I ran a bit short on time this weekend. I will try to look at it hopefully on thursday.

**Comment by cromerc** [comment]
I have been looking through the elogind code, and it looks like the just call halt, reboot, poweroff directly. I don't see any parameters being used.

However reading through the sysvinit man page I noticed something which I think is the problem that @udeved has:

`From  release  2.74 on halt and reboot invoke shutdown(8) if
       the system is not in runlevel 0 or 6.`

What I believe is happening is that elogind is calling halt, however openrc-init does not behave like sysvinit. What I notice in openrc-init.c is that it calls RB_HALT_SYSTEM, however sysvinit doesn't call halt, it calls shutdown which should behave similar to "poweroff".

**Comment by cromerc** [comment]
@udeved Can you test to confirm my theory, simply modify the "halt" script from openrc and make it call poweroff. See if that fixes things.

**Comment by udeved** [comment]
@cromerc  @williamh 

Chris' proposed fix works for me, the machine powers off correctly.

`sed -e 's|--halt|--poweroff|' -i  path/to/halt
`
does the job.

**Comment by cromerc** [comment]
If true sysvinit compat is the goal then halt should redirect to poweroff. Even though I find it to be a dirty hack, it is what sysvinit does. :/

The other problem is that elogind incorrectly calls halt when they should be calling poweroff. So an issue should be opened with elogind as well.
