### ISSUE TITLE
man/openrc-run.8: document the _pre and _post functions

### ISSUE THREAD

**Issue by orlitzky** [OpenRC/openrc#155]
The example init script in the openrc-run man page demonstrates some `_pre` and `_post` phase functions. For example,

```bash
stop_post() {
    # Clean any spills
    rm -rf /var/cache/foo/*
}
```

At least all of the following work: `start_pre`, `start_post`, `stop_pre`, and `stop_post`. However, the `_pre` and `_post` phases aren't documented anywhere else -- in particular, they're missing from the list at the very beginning of the man page. It would be good to mention them, perhaps along with the documentation for `start()` and `stop()`, if those are the  only two phases that get a `_pre` and `_post`.

**Comment by williamh** [comment]
I'll need to figure out where to document this in the openrc-run man page, because actually the scope goes further than just start/stop. Any command you define in the *_commands variable can have a _pre or _post function.
