### ISSUE TITLE
cgroups v2 errors

### ISSUE THREAD

**Issue by cromerc** [OpenRC/openrc#164]
Testing out the new 0.31, it is generating some issues if I use "hybrid" cgroups.
This is the output:
```
* Caching service dependencies ... [ok]
mkdir: cannot create directory '/sys/fs/cgroup/unified/devfs': No such file or directory
/usr/lib/openrc/rc-cgroup.sh: line 189: /sys/fs/cgroup/unified/devfs/cgroup.procs: No such file or directory
* Remounting devtmpfs on /dev ... [ok]
* Mounting /dev/mqueue ... [ok]
* Mounting /dev/pts ... [ok]
* Mounting /dev/shm ... [ok]
mkdir: cannot create directory '/sys/fs/cgroup/unified/dmesg': No such file or directory
/usr/lib/openrc/rc-cgroup.sh: line 189: /sys/fs/cgroup/unified/dmesg/cgroup.procs: No such file or directory
mkdir: cannot create directory '/sys/fs/cgroup/unified/sysfs': No such file or directory
/usr/lib/openrc/rc-cgroup.sh: line 189: /sys/fs/cgroup/unified/sysfs/cgroup.procs: No such file or directory
```

**Comment by bitlord** [comment]
I'm also having this issue on my gentoo ~amd64 box. What is most likely related is the message I get later:
```
 * Mounting cgroup filesystem ...
 [ ok ]
mount: /sys/fs/cgroup/unified: wrong fs type, bad option, bad superblock on none, missing codepage or helper program, or other error.
 * Starting udev ...
```

**Comment by williamh** [comment]
What versions of the kernel are you running? from what I've read cgroups v2 isn't considered officially stable until linux-4.13, and I thought I put enough checks in the code to be sure that it wasn't enabled for older versions.

**Comment by bitlord** [comment]
@williamh I'm running linux-4.9.50 at the moment. Does this mean I need to tweak /etc/rc.conf and set rc_cgroup_mode to legacy?

Thanks.

**Comment by cromerc** [comment]
@williamh I get the same error messages on 2 different kernels, 4.9.50 and 4.13.2.

**Comment by williamh** [comment]
I found something as well, I'm looking at a patch to sysfs that will make hybrid fall back to legacy if cgroups2 isn't enabled.

**Comment by williamh** [comment]
It looks like the nsdelegate mount option for cgroups2 is at least part of the problem, that isn't supported until 4.13.

**Comment by williamh** [comment]
@bitlord I'm looking at a patch to allow hybrid to fall back to legacy if cgroups version 2 is not enabled in the kernel.

**Comment by cromerc** [comment]
But in the case of 4.13.2 hybrid should be working and not showing these errors correct? Or is this due from a miss-configuration of the kernel?

In the config file for the 4.13.2 kernel I don't see any option related to cgroups v2, is there a special config option that I need to enable?

**Comment by williamh** [comment]
@cronerc you are right, I don't see one either. If you run this command, do you get any output:
```
grep -w cgroup2 /proc/filesystems
```

**Comment by cromerc** [comment]
I get this output on both 4.9.50 and 4.13.2
`nodev    cgroup2`

**Comment by williamh** [comment]
@cromerc That appears to be correct. @bitlord you should be able to verify the same.
I even more strongly suspect the nsdelegate mount option for cgroups2 is the issue. It looks like I need to try to mount with the option then without it.
What is the status of CONFIG_NAMESPACES in your kernels?

**Comment by bitlord** [comment]
@williamh I also have cgroup2 present in /proc/filesystems and for CONFIG_NAMESPACES I have it built-in. ( CONFIG_NAMESPACES=y )

**Comment by cromerc** [comment]
I have it configured with:
CONFIG_NAMESPACES=y

Here is the config files if you want to see any other config settings:
4.9.50: https://github.com/cromnix/packages/blob/master/main/linux/config
4.13.2: https://github.com/cromnix/packages/blob/master/main/linux-stable/config

**Comment by williamh** [comment]
I'm working on a patch, give me a few minutes and I'll update.

**Comment by williamh** [comment]
@bitlord @cromerc Please test with the following patch and report back.

https://paste.pound-python.org/raw/OPXMluwvpXjOuRqU1uwK/

**Comment by bitlord** [comment]
@williamh I applied the patch but I still get those error messages for "No such file or directory".
Not sure how this work internally, but now after boot there is something at /sys/fs/cgroup/unified, 
but when you look at /var/log/rc.log it shows up that cgroup filesystems are mounted after it tries to create those directories, I'm not sure is this just the output or it happens in wrong order:

```
   OpenRC 0.31 is starting up Gentoo Linux (x86_64)

 * /proc is already mounted
 * Mounting /run ...
 * /run/openrc: creating directory
 * /run/lock: creating directory
 * /run/lock: correcting owner
 * Caching service dependencies ...
 [ ok ]
mkdir: cannot create directory ‘/sys/fs/cgroup/unified/devfs’: No such file or directory
/lib64/rc/sh/rc-cgroup.sh: line 191: /sys/fs/cgroup/unified/devfs/cgroup.procs: No such file or directory
 * Remounting devtmpfs on /dev ...
 [ ok ]
 * Mounting /dev/mqueue ...
 [ ok ]
 * Mounting /dev/shm ...
 [ ok ]
mkdir: cannot create directory ‘/sys/fs/cgroup/unified/dmesg’: No such file or directory
/lib64/rc/sh/rc-cgroup.sh: line 191: /sys/fs/cgroup/unified/dmesg/cgroup.procs: No such file or directory
mkdir: cannot create directory ‘/sys/fs/cgroup/unified/kmod-static-nodes’: No such file or directory
/lib64/rc/sh/rc-cgroup.sh: line 191: /sys/fs/cgroup/unified/kmod-static-nodes/cgroup.procs: No such file or directory
 * Creating list of required static device nodes for the current kernel ...
 [ ok ]
mkdir: cannot create directory ‘/sys/fs/cgroup/unified/opentmpfiles-dev’: No such file or directory
/lib64/rc/sh/rc-cgroup.sh: line 191: /sys/fs/cgroup/unified/opentmpfiles-dev/cgroup.procs: No such file or directory
 * Setting up tmpfiles.d entries for /dev ...
 [ ok ]
mkdir: cannot create directory ‘/sys/fs/cgroup/unified/sysfs’: No such file or directory
/lib64/rc/sh/rc-cgroup.sh: line 191: /sys/fs/cgroup/unified/sysfs/cgroup.procs: No such file or directory
 * Mounting debug filesystem ...
 [ ok ]
 * Mounting fuse control filesystem ...
 [ ok ]
 * Mounting cgroup filesystem ...
 [ ok ]
...
```

Content of /sys/fs/cgroup/unified after patch is applied 

```
quad ~ # ls -1 /sys/fs/cgroup/unified/
bluetooth
cgroup.controllers
cgroup.procs
cgroup.subtree_control
consolekit
cronie
dbus
distccd
libvirtd
lvmetad
mcelog
syslog-ng
udev
virtlogd
xdm

```

**Comment by williamh** [comment]
@bitlord OK, that's a separate issue, but we got cgroups mounted. I'll work on a fix for that in the same patch.

**Comment by williamh** [comment]
@bitlord @cromerc Try this patch.

https://paste.pound-python.org/raw/BKzhHWfdRAWhagb6Rcdz/

**Comment by bitlord** [comment]
@williamh new patch seems to resolve all issues with warnings/errors during boot. Since I know nothing about cgroups, I cannot say about functionality, for me everything looks good, and works fine.

Thanks!

**Comment by bitlord** [comment]
@williamh forgot to add that in kernel log now you can find:
`[   16.179735] cgroup: cgroup2: unknown option "nsdelegate"
`
I guess that is related to that first try to mount cgroup2, and when it fails it mounts without 'nsdelgate' option.

**Comment by cromerc** [comment]
The patch took care of the errors. I don't know whether or not cgroups is working or not, I don't have it implemented in Cromnix yet.

**Comment by williamh** [comment]
@bitlord you are correct about what that message means. Currently I'm not sure of a way to know whether I can use the nsdelegate option without trying it and failing, so that message is harmless.
