### ISSUE TITLE
support meson buildsystem

### ISSUE THREAD

**Issue by liugang** [OpenRC/openrc#172]
With #171 Openrc can build with meson, now

Usage:
```
pip3 install meson

wget https://github.com/ninja-build/ninja/releases/download/v1.8.2/ninja-linux.zip
unzip -x ninja-linux.zip
chmod 755 ninja
cp ninja /usr/local/bin

meson builddir
ninja -C builddir
DESTDIR=out ninja -C builddir install
```

`ninja check` same as make check/test, but can't work, now, it need update shell scripts.

`ninja test` , can run all unit tests case,  see: http://mesonbuild.com/Unit-tests.html

These command can be use to developer to debug:
`meson test --wrap=valgrind testname`, `meson test --gdb testname`, `meson test --repeat=10`

you can generate coverage reports by giving Meson the command line flag -Db_coverage=true 
```
meson -Db_coverage=true builddir; 
ninja -C builddir test
```

cross compile:

just write a config file like below: e.g. crossbuild.ini
```
[binaries]
c = '/usr/bin/arm-linux-gnueabi-gcc'
cpp = '/usr/bin/arm-linux-gnueabi-g++'
ar = '/usr/bin/arm-linux-gnueabi-ar'
strip = '/usr/bin/arm-linux-gnueabi-strip'

[host_machine]
system = 'linux'
cpu_family = 'arm'
cpu = 'arm'
endian = 'little'
```

and run `meson builddir --cross-file crossbuild.ini`

**Comment by williamh** [comment]
Yes, I'm working on this, it is just on my personal fork of the project on a branch. I haven't put it in the mainline because it isn't complete yet.

**Comment by liugang** [comment]
I have commited a PR #171, It works now

**Comment by williamh** [comment]
Mine is #175.

It isn't quite complete yet, but I like parts of yours, so let's combine forces and make this happen. :-)

I will be looking through yours, and I will combine ideas from both of our pull requests into the final build files.

**Comment by liugang** [comment]
OK
