### ISSUE TITLE
openrc-init: Request for SELinux support

### ISSUE THREAD

**Issue by holgersson32644** [OpenRC/openrc#173]
Hi,
when booting with init=/sbin/openrc-init on Gentoo SELinux is broken (all files are shown as "unlabeled" etc.). In the #gentoo-hardened IRC channel I was informed that there is some functionality needed for SELinux with openrc-init:

> aranea: selinux_init_load_policy() from libselinux should perform all neccessary operations, but I think init needs to re-exec itself afterwards to transition from kernel_t to init_t, which makes the whole thing a little ugly.
> aranea: That can either be solved by splitting init into two separate executables (that's what I do for my init impl), or by re-exec'ing itself with a special variable in the environ; that's what sysvinit does (IIRC).
> aranea: I should also point out that selinux_init_load_policy has side effects beyond setting up selinux; it mounts /proc and /sys, unless they're already mounted.

An implementation of this would be great :)

Edit: Actually it was #gentoo-hardened, not #openrc ;-)

**Comment by williamh** [comment]
I haven't forgotten about this issue; I have had several other things going on.
I am about to commit a patch to master that references this issue, please test and report back.
If it works, we can close this issue.

**Comment by williamh** [comment]
I understand from the #gentoo-hardened irc channel that this works, so it will be included in 0.40.
