### ISSUE TITLE
start-stop-daemon: can't stop daemon running using non-root user inside lxc container with sys_ptrace capability dropped

### ISSUE THREAD

**Issue by iDarkTemplar** [OpenRC/openrc#180]
Openrc version 0.34.5.

Steps to reproduce:

1) use lxc-2.* (not sure if it reproduces with other versions, I've tried only 2.0.8 and 2.1.1)
2) create gentoo container (lxc-create -n $name -t gentoo)
3) add to container config:
lxc.mount.entry=run run tmpfs rw,nosuid,nodev,relatime,mode=755 0 0
lxc.cap.drop = sys_ptrace
4) add network to config and run container
5) run 'ACCEPT_KEYWORDS="~*" emerge -1 openrc' inside container
6) add line to etc/rc.conf inside container:
rc_sys="lxc"
7) restart container, attach to it and do rest of steps inside of container
8) emerge dev-vcs/git
9) mkdir /var/git
10) /etc/init.d/git-daemon start
11) /etc/init.d/git-daemon stop

Stop action fails.

Without 'sys_ptrace' capability start-stop-daemon can't find out cgroups namespace of process belonging to another user when pid is provided, and thus fails to stop daemon. I'm also dropping other capabilities like sys_admin, but dropping this one specifically make openrc fail. If I rerun start-stop-daemon command again manually after that, it successfully stops git-daemon (since there's no longer a pidfile present, and it looks using other identifiers), but since it uses executable name, it will just kill every git daemon process.

```
test4 ~ # /etc/init.d/git-daemon status
 * status: started
test4 ~ # whoami
root
test4 ~ # ps aux | grep git
nobody     306  0.0  0.0  17052  1068 ?        Ss   12:58   0:00 /usr/bin/git daemon --syslog --base-path=/var/git
nobody     309  0.0  0.0  16044   988 ?        S    12:58   0:00 /usr/libexec/git-core/git-daemon --syslog --base-path=/var/git
root       341  0.0  0.0  10708   968 ?        S+   13:02   0:00 grep --colour=auto git
test4 ~ # ls -la /proc/306/ns
ls: cannot read symbolic link '/proc/306/ns/net': Permission denied
ls: cannot read symbolic link '/proc/306/ns/uts': Permission denied
ls: cannot read symbolic link '/proc/306/ns/ipc': Permission denied
ls: cannot read symbolic link '/proc/306/ns/pid': Permission denied
ls: cannot read symbolic link '/proc/306/ns/pid_for_children': Permission denied
ls: cannot read symbolic link '/proc/306/ns/user': Permission denied
ls: cannot read symbolic link '/proc/306/ns/mnt': Permission denied
ls: cannot read symbolic link '/proc/306/ns/cgroup': Permission denied
total 0
dr-x--x--x 2 nobody nobody 0 Nov  5 12:58 .
dr-xr-xr-x 9 nobody nobody 0 Nov  5 12:58 ..
lrwxrwxrwx 1 nobody nobody 0 Nov  5 12:58 cgroup
lrwxrwxrwx 1 nobody nobody 0 Nov  5 12:58 ipc
lrwxrwxrwx 1 nobody nobody 0 Nov  5 12:58 mnt
lrwxrwxrwx 1 nobody nobody 0 Nov  5 12:58 net
lrwxrwxrwx 1 nobody nobody 0 Nov  5 12:58 pid
lrwxrwxrwx 1 nobody nobody 0 Nov  5 12:58 pid_for_children
lrwxrwxrwx 1 nobody nobody 0 Nov  5 12:58 user
lrwxrwxrwx 1 nobody nobody 0 Nov  5 12:58 uts
test4 ~ # su - nobody -s /bin/bash -c 'whoami'
nobody
test4 ~ # su - nobody -s /bin/bash -c 'ls -la /proc/306/ns'
total 0
dr-x--x--x 2 nobody nobody 0 Nov  5 12:58 .
dr-xr-xr-x 9 nobody nobody 0 Nov  5 12:58 ..
lrwxrwxrwx 1 nobody nobody 0 Nov  5 12:58 cgroup -> cgroup:[4026532788]
lrwxrwxrwx 1 nobody nobody 0 Nov  5 12:58 ipc -> ipc:[4026532711]
lrwxrwxrwx 1 nobody nobody 0 Nov  5 12:58 mnt -> mnt:[4026532709]
lrwxrwxrwx 1 nobody nobody 0 Nov  5 12:58 net -> net:[4026532714]
lrwxrwxrwx 1 nobody nobody 0 Nov  5 12:58 pid -> pid:[4026532712]
lrwxrwxrwx 1 nobody nobody 0 Nov  5 12:58 pid_for_children -> pid:[4026532712]
lrwxrwxrwx 1 nobody nobody 0 Nov  5 12:58 user -> user:[4026531837]
lrwxrwxrwx 1 nobody nobody 0 Nov  5 12:58 uts -> uts:[4026532710]
test4 ~ # /etc/init.d/git-daemon stop
 * No permission to apply cgroup settings
 * Stopping git-daemon ...
 * start-stop-daemon: no matching processes found       
test4 ~ # ps aux | grep git
nobody     306  0.0  0.0  17052  1068 ?        Ss   12:58   0:00 /usr/bin/git daemon --syslog --base-path=/var/git
nobody     309  0.0  0.0  16044   988 ?        S    12:58   0:00 /usr/libexec/git-core/git-daemon --syslog --base-path=/var/git
root       373  0.0  0.0  10708   816 ?        S+   13:06   0:00 grep --colour=auto git
```

EDIT: sys_ptrace capability is dropped by default in gentoo.moresecure.conf

**Comment by williamh** [comment]
Hi, can you test with OpenRC 0.34.6 and let me know if the issue still exists?

**Comment by williamh** [comment]
Also, did this ever work with older versions of OpenRC?

**Comment by iDarkTemplar** [comment]
I've tested OpenRC 0.34.6 and issue still exists.
I didn't know if earlier versions of OpenRC handled it correctly, so I tried them out.
Following versions are NOT affected by current issue: 0.27.2, 0.32.1, 0.33.1.
Following versions are affected by current issue: 0.34, 0.34.5, 0.34.6.

**Comment by iDarkTemplar** [comment]
I think the issue is caused by fix for https://bugs.gentoo.org/show_bug.cgi?id=634634
The check for cgroups namespace was added, but with sys_ptrace privilege dropped OpenRC can't look up the cgroup namespace of process owned by another user, at least not the way it currently is implemented. You can see it in the code block in my first message. I've checked it, and pid 1 in LXC container (owned by 'root' user) has same namespaces as git daemon process (owned by 'nobody' user), but since it belongs to another user, you lack permissions to read the value.

**Comment by williamh** [comment]
Does anyone have any suggestions for how to handle this?
I don't run lxc, so I'm not quite sure what the answer should be.

**Comment by iDarkTemplar** [comment]
I thought that changing effective uid to user owning pid would help, but it didn't work until I also changed effective gid too.

Here are pull requests that together fix issue for me with git-daemon inside lxc container with sys_ptrace capability dropped:
https://github.com/OpenRC/openrc/pull/181
https://github.com/gentoo/gentoo/pull/6176

**Comment by williamh** [comment]
Hi, can you apply this patch and let me know if it resolves the issue?

http://dpaste.com/39WX0J3.txt

Thanks,

William

**Comment by iDarkTemplar** [comment]
Hi. This change also resolves the issue for me, although I can't say I like this approach more.
