### ISSUE TITLE
build broken on FreeBSD-CURRENT r326056 snapshot as of 0.34

### ISSUE THREAD

**Issue by pkgdemon** [OpenRC/openrc#186]
```
start-stop-daemon.c:642:20: warning: expression which evaluates to zero treated as a null pointer constant of type
      'char *' [-Wnon-literal-null-conversion]
                                nav[i + len] = '\0';
                                               ^~~~
1 warning generated.
cc  -L../librc -L../libeinfo -O2 -g -std=c99 -Wall -Wextra -Wimplicit -Wshadow -Wformat=2 -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -Wmissing-format-attribute -Wnested-externs -Winline -Wwrite-strings -Wcast-align -Wcast-qual -Wpointer-arith -Wdeclaration-after-statement -Wsequence-point -Werror=implicit-function-declaration    -Wl,-rpath=/lib   -o start-stop-daemon start-stop-daemon.o _usage.o rc-misc.o rc-schedules.o -lutil -lrc -leinfo  -lkvm
cc  -I../includes -I../librc -I../libeinfo -O2 -g -std=c99 -Wall -Wextra -Wimplicit -Wshadow -Wformat=2 -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -Wmissing-format-attribute -Wnested-externs -Winline -Wwrite-strings -Wcast-align -Wcast-qual -Wpointer-arith -Wdeclaration-after-statement -Wsequence-point -Werror=implicit-function-declaration    -c supervise-daemon.c -o supervise-daemon.o
supervise-daemon.c:162:13: error: static declaration of 're_exec' follows non-static declaration
static void re_exec(void)
            ^
/usr/include/unistd.h:550:6: note: previous declaration is here
int      re_exec(const char *);
         ^
supervise-daemon.c:182:11: error: too few arguments to function call, expected 1, have 0
                re_exec();
                ~~~~~~~ ^
/usr/include/unistd.h:550:1: note: 're_exec' declared here
int      re_exec(const char *);
^
supervise-daemon.c:438:23: error: use of undeclared identifier 'SIGPOLL'
        signal_setup_restart(SIGPOLL, handle_signal);
                             ^
supervise-daemon.c:449:23: error: use of undeclared identifier 'SIGPWR'
        signal_setup_restart(SIGPWR, handle_signal);
                             ^
supervise-daemon.c:450:23: error: use of undeclared identifier 'SIGUNUSED'
        signal_setup_restart(SIGUNUSED, handle_signal);
                             ^
5 errors generated.
gmake[2]: *** [../../mk/prog.mk:35: supervise-daemon.o] Error 1
gmake[2]: Leaving directory '/usr/home/jmaloney/projects/openrc/openrc/src/rc'
gmake[1]: *** [../mk/subdir.mk:26: all] Error 2
gmake[1]: Leaving directory '/usr/home/jmaloney/projects/openrc/openrc/src'
gmake: *** [/usr/home/jmaloney/projects/openrc/openrc//mk/subdir.mk:26: all] Error 2
```
0.31 is the latest version that I am able to build with gmake.  Every build starting with 0.34 produces the errors shown above.

**Comment by williamh** [comment]
Hi, please test with 0.34.10. This release should fix those issues.

**Comment by williamh** [comment]
@pkgdemon see previous comment. Please update this issue after you attempt to build 0.34.10.

**Comment by williamh** [comment]
@pkgdemon Hi, the latest is now 0.34.11. Please attempt to build this version on FreeBSD. It should fix the issues you reported. I am closing this issue, but please feel free to comment  and let me know if it is not fixed.

Thanks much,

William

**Comment by zdavatz** [comment]
On my pandaboard, armv7 I am still getting this error with openrc 0.34.11
``
 -Wall -Wextra -Wimplicit -Wshadow -Wformat=2 -Wmissing-prototypes -Wmissing-declarations -Wmissing-noreturn -Wmissing-format-attribute -Wnested-externs -Winline -Wwri
te-strings -Wcast-align -Wcast-qual -Wpointer-arith -Wdeclaration-after-statement -Wsequence-point -Werror=implicit-function-declaration   -c libeinfo.c -o libeinfo.So
libeinfo.c: In function 'elogv':
libeinfo.c:525:3: error: implicit declaration of function 'vsyslog'
libeinfo.c:525:3: warning: nested extern declaration of 'vsyslog'
make[2]: *** [libeinfo.So] Error 1
make[2]: Leaving directory `/var/tmp/portage/sys-apps/openrc-0.34.11/work/openrc-0.34.11/src/libeinfo'
make[1]: *** [all] Error 2
make[1]: Leaving directory `/var/tmp/portage/sys-apps/openrc-0.34.11/work/openrc-0.34.11/src'
make: *** [all] Error 2
```
/etc/make.conf says:
```
CFLAGS="-O2 -pipe -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=hard"
CXXFLAGS="${CFLAGS}"
CHOST="armv7a-hardfloat-linux-gnueabi"
USE="-* X apache2 apng avahi cairo curl fltk gd git hash imagemagick jpeg
     libxml2 linguas_de_CH mysql opengl pango php png sdl session tiff unicode ipc
     wxwidgets zlib -cups -ffi -v8 -xinerama -tinfo"
```
any hints?

**Comment by williamh** [comment]
@zdavatz It looks like vsyslog is not defined on your system for some reason. Which OS are you using?

**Comment by zdavatz** [comment]
Gentoo.

**Comment by williamh** [comment]
Gentoo FreeBSD? (I'm asking because this bug was for FreeBSD builds failing).

**Comment by zdavatz** [comment]
Sorry, not not FreeBSD. You can keep this closed.

**Comment by williamh** [comment]
Please feel free to open another issue. My suspicion is that your glibc may not be up to date, but I'm not sure. Please make sure  you are running the latest stable glibc.

**Comment by zdavatz** [comment]
Yes upgrading glibc did the job. Thank you!
