### ISSUE TITLE
OpenRC in Parabola GNU system: drive partition refreshing

### ISSUE THREAD

**Issue by ghost** [OpenRC/openrc#193]
Since few days ago my Parabola GNU system with OpenRC init system has been suffered against UUID panic in its GRUB, I was needed to probe the new UUID to help to fix that, having probed the new UUID OpenRC doesnt refresh to my new UUID, but how to instruct OpenRC to also refresh this new UUID, that has been manually refreshed under my /etc/fstab?

**Comment by williamh** [comment]
@hd-scania I don't understand your question. If fstab is correct, that is where OpenRC looks, it just uses mount/umount to control things and they use fstab.

Can you give more information about the issue you are experiencing?

**Comment by hd-scania** [comment]
My fstab has been always profound refreshed but,
~~~
E: /dev/disk/by-uuid/$MYNEWUUID not found, given up to wait
Now you are dropt into an emergency shell
[root@hd-scania]#
~~~
Do I just remount my system using?
~~~
# mount /dev/sda6 / -o rw,remount &&
~~~
But if this is still failed, I have a Parabola ISO and using arch-chroot command to further fix this.
After entering my Parabola ISO I will be back to here and ask for more here.

**Comment by arescorpio** [comment]
https://torrent.resonatingmedia.com/torrents/parabola-openrc-cli-dual-complete-2018.06.11.iso.c939d6fcd1780dac.torrent # done!

**Comment by vapier** [comment]
as noted, this doesn't sound like an OpenRC issue.  feel free to post more details.
