### ISSUE TITLE
Umask is ignored within `supervise-daemon`

### ISSUE THREAD

**Issue by concatime** [OpenRC/openrc#198]
From my test, it seems that `umask` is not working. Maybe I'm doing something wrong?
```
 # supervise-daemon --version
supervise-daemon (OpenRC) 0.24.1.a941ee4a0b
```
```
 # rm -f /tmp/whyNot && supervise-daemon --user web --pidfile /run/web.pid --umask 077 touch /tmp/whyNot && sleep .1 && ls -l /tmp/whyNot && kill `cat /run/web.pid`
-rw-r--r--    1 web      www-data         0 Jan  3 22:03 /tmp/whyNot
```
```
 # rm -f /tmp/whyNot && start-stop-daemon --user web --pidfile /run/web.pid --umask 077 touch /tmp/whyNot && sleep .1 && ls -l /tmp/whyNot
-rw-------    1 web      www-data         0 Jan  3 22:03 /tmp/whyNot
```
Thank you.

**Comment by williamh** [comment]
Is this still an issue in OpenRC 0.34.11?

**Comment by concatime** [comment]
Sorry, but I have to wait for an update of openrc from Alpine before giving you a correct answer. The package is currently flagged (November, 30) as marked [here](//pkgs.alpinelinux.org/packages?name=openrc&branch=edge&arch=x86_64).

**Comment by williamh** [comment]
I don't see this happening with the master branch, so it should be taken care of in 0.35.
