### ISSUE TITLE
service-script-guide.md: the discussion about /var/run and /run is misleading

### ISSUE THREAD

**Issue by williamh** [OpenRC/openrc#202]
@orlitzky The discussion in the service script guide about pid files is not quite correct. /var/run is required to exist by the FHS, so there are no plans that I am aware of to remove it from Linux.

Also, the recommendation to use the upstream build system for an OS specific setting is not necessary because the service script can check the RC_UNAME environment variable at runtime if it needs to to anything OS specific.

**Comment by orlitzky** [comment]
> The discussion in the service script guide about pid files is not quite correct. /var/run is required to exist by the FHS, so there are no plans that I am aware of to remove it from Linux.

It's in the FHS, but deprecated in favor of `/run`:

> **5.13. /var/run : Run-time variable data**
> _5.13.1. Purpose_
> This directory was once intended for system information data describing the system since it was booted. These functions have been moved to /run; ...

Autoconf now has a `--runstatedir` flag to be used for that purpose, and Gentoo is slowly moving away from `/var/run` (although the symlink will have to stick around until all of the packages in the tree are updated):

* https://bugs.gentoo.org/332633
* https://bugs.gentoo.org/361349
* https://bugs.gentoo.org/589248

The other major distros have switched already, particularly those on systemd.

> Also, the recommendation to use the upstream build system for an OS specific setting is not necessary because the service script can check the RC_UNAME environment variable at runtime if it needs to to anything OS specific.

But wouldn't it be pretty ugly to have a big case statement at the top of every service script trying to guess where to put the PID file? Especially considering that build system already knows (thanks to `--runstatedir`, or one of the custom `--with-piddir` flags that people have invented).

We don't use `RC_UNAME` for any of the other settings that the build system knows about (bindir, libdir, runstatedir, etc.)

**Comment by williamh** [comment]
http://refspecs.linux-foundation.org/FHS_3.0/fhs-3.0.html
http://refspecs.linux-foundation.org/FHS_3.0/fhs-3.0.html#varrunRuntimeVariableData

I see a couple of things here. In the FHS, the table of contents flags optional items and /var/run isn't  listed as one of them.
However, section 5.13.2 says it is valid to implement /var/run as a symlink to /run.
The way I read this, /var/run will not go away, but programs will not use it directly. I will take a look at the documentation again.

**Comment by orlitzky** [comment]
Which part of the service script guide do you think is misleading w.r.t. `/var/run`? IMO the most important point is

> The directory that should contain the PID file is best determined by the upstream build system (see "Upstream your service scripts"). On Linux, the preferred location these days is /run. Other systems still use /var/run, though, and a ./configure script is the best place to decide which one you want.

If everyone does that, then the symlink is superfluous, but doesn't hurt anything. And on systems that still use `/var/run` (as a real directory) instead of `/run`, the packager will point the build system to `/var/run` and everything's happy.

**Comment by williamh** [comment]
I am closing this because it seems to be resolved.
