### ISSUE TITLE
to not set a running service to stop state

### ISSUE THREAD

**Issue by toralf** [OpenRC/openrc#203]
The origin is here : https://bugs.gentoo.org/644982 but here the development is made, so again : 

At a stable Gentoo Linux OpenRC wrongly reported today that the service "tor" is crashed.

A (by accident run) "/etc/init.d/tor start" gave:
`
 * Starting tor ...
 * start-stop-daemon: /usr/bin/tor is already running

 * Failed to start tor
                                                   [ !! ]
 * ERROR: tor failed to start
 * Manually resetting tor to stopped state
`

IMO it should not set a service to "stop" if it detected that it is "started".

BTW is there any chance to manually fix the status in such a case at the command line ?

**Comment by williamh** [comment]
I haven't looked at this yet, but I suspect the tor init script more than OpenRC per se.

**Comment by williamh** [comment]
I tried to reproduce this with openrc-9999 and got the following:

```
linux1 ~ # openrc --version
openrc (OpenRC) 0.35git-110582 (Gentoo Linux)
linux1 ~ # rc-service tor start
 * Starting tor ... [ ok ]
linux1 ~ # rc-service tor start
 * WARNING: tor has already been started
linux1 ~ # rc-status | grep tor
 tor                                                               [  started  ]
linux1 ~ # rc-service tor status
 * status: started
linux1 ~ # rc-service tor stop
 * Stopping tor ... [ ok ]
linux1 ~ #
```

So, it seems to not be an issue in current master. I would guess that something happened to the pid file.


Thanks,

William
