### ISSUE TITLE
agetty 1-6 not starting with version 0.35

### ISSUE THREAD

**Issue by cimarronline** [OpenRC/openrc#212]
With version 0.35 (and 0.35.1) I see this error repeatedly at the end of booting:
> 
`/usr/lib/openrc/sh/openrc-run.sh: line 36: /etc/in: No such file or directory`

And `rc-status` shows agetty.tty1-6 stopped (only the desktop on tty7 is available). Attempting `rc-service agetty.tty2 start` results in the same error and fails to start. Version 0.34.11 works fine.

**Comment by williamh** [comment]
Please provide the output from:

```
# /etc/init.d/agetty.tty2 --debug start
```

Thanks,

William

**Comment by cromerc** [comment]
@williamh Not sure if it is related, but we got somebody with something similar with 0.35 on artix linux:
https://forum.artixlinux.org/index.php/topic,440.msg3460.html#new

**Comment by cimarronline** [comment]
```
[manjaro ~]# /etc/init.d/agetty.tty2 --debug start
+ sourcex -e /etc/rc.conf
+ '[' -e = -e ']'
+ shift
+ '[' -e /etc/rc.conf ']'
+ . /etc/rc.conf
++ rc_interactive=YES
++ rc_logger=YES
++ unicode=YES
++ rc_tty_number=12
++ rc_cgroup_mode=legacy
+ '[' -d /etc/rc.conf.d ']'
+ _conf_d=/etc/../conf.d
+ _c=in
+ '[' -n in -a in '!=' in ']'
+ unset _c
+ sourcex -e /etc/../conf.d/in.default
+ '[' -e = -e ']'
+ shift
+ '[' -e /etc/../conf.d/in.default ']'
+ return 1
+ sourcex -e /etc/../conf.d/in
+ '[' -e = -e ']'
+ shift
+ '[' -e /etc/../conf.d/in ']'
+ return 1
+ unset _conf_d
+ sourcex /usr/lib/openrc/sh/runit.sh
+ '[' /usr/lib/openrc/sh/runit.sh = -e ']'
+ . /usr/lib/openrc/sh/runit.sh
+ sourcex /usr/lib/openrc/sh/s6.sh
+ '[' /usr/lib/openrc/sh/s6.sh = -e ']'
+ . /usr/lib/openrc/sh/s6.sh
++ '[' -z '' ']'
++ s6_service_path=/var/svc.d/in
+ sourcex /usr/lib/openrc/sh/start-stop-daemon.sh
+ '[' /usr/lib/openrc/sh/start-stop-daemon.sh = -e ']'
+ . /usr/lib/openrc/sh/start-stop-daemon.sh
+ sourcex /usr/lib/openrc/sh/supervise-daemon.sh
+ '[' /usr/lib/openrc/sh/supervise-daemon.sh = -e ']'
+ . /usr/lib/openrc/sh/supervise-daemon.sh
+ sourcex /etc/in
+ '[' /etc/in = -e ']'
+ . /etc/in
/usr/lib/openrc/sh/openrc-run.sh: line 36: /etc/in: No such file or directory
 * ERROR: in failed to start

```

**Comment by williamh** [comment]
I need to make sure you are using the vanilla upstream code, so do you have any patches applied to OpenRC that I'm not aware of? I am asking because I just started an agetty with no issues.

**Comment by cimarronline** [comment]
No patches. Here's the build options used, and setting up agetty (from the PKGBUILD):
```

_args=(
    SYSCONFDIR=/etc
    PREFIX=/usr
    SBINDIR=/usr/bin
    LIBEXECDIR=/usr/lib/openrc
    MKSELINUX=no
    MKPAM=pam
    MKTERMCAP=ncurses
    MKNET=no
    MKSYSVINIT=yes
)
```

```

    # getty
    sed -e 's|#baud=""|baud="38400"|' \
        -e 's|#term_type="linux"|term_type="linux"|' \
        -e 's|#agetty_options=""|agetty_options=""|' \
        -i ${pkgdir}/etc/conf.d/agetty

    for num in 1 2 3 4 5 6;do
        cp -v ${pkgdir}/etc/conf.d/agetty ${pkgdir}/etc/conf.d/agetty.tty$num
        ln -sf /etc/init.d/agetty ${pkgdir}/etc/init.d/agetty.tty$num
        ln -sf /etc/init.d/agetty.tty$num ${pkgdir}/etc/runlevels/default/agetty.tty$num
    done

```

**Comment by cromerc** [comment]
In the case of Artix Linux we don't use any patches, the code that @cimarronline put for the getties is the same as ours at artix. I also have no issue with OpenRC 0.35 and the agettys, so not sure if it is something that our user modified or if it fails under certain circumstances.

**Comment by williamh** [comment]
@cromerc Is your build the same as well, do you customize sbindir and libexecdir?

**Comment by williamh** [comment]
The agetty man page says that the port comes before the baud rate on the command line, but our inittab shows it the other way around. Can someone test what happens if you reverse the order of the port and baud rate in /etc/init.d/agetty on the command_args_foreground line?

**Comment by cromerc** [comment]
@williamh Here is our build:
```
    SYSCONFDIR=/etc
    PREFIX=/usr
    SBINDIR=/usr/bin
    LIBEXECDIR=/usr/lib/openrc
    MKSELINUX=no
    MKPAM=pam
    MKTERMCAP=ncurses
    MKNET=no
    MKSYSVINIT=yes
    MKBASHCOMP=yes
    MKZSHCOMP=yes
```

I will change the baud rate line in `/etc/init.d/agetty` and let you know what happens.

**Comment by cromerc** [comment]
Just tried out switching baud and port in my agetty init script. It made no difference at all. Start up and shutdown worked just fine for me on 0.35 with port and baud in any order.

**Comment by cimarronline** [comment]
I switched the order in the command_args_foreground line to:
`command_args_foreground="${agetty_options} ${baud} ${port} ${term_type}"`

But attempting to start the agetty.tty2 service failed with the same error.

**Comment by cimarronline** [comment]
Seems like you're right. When, for example, I use a copy for the /etc/init.d/agetty.tty2 file instead of a symlink, I can start the agetty.tty2 service properly.

**Comment by cromerc** [comment]
PR #213 fixes this issue.
