### ISSUE TITLE
openrc[1789]: Error: fopen(/run/openrc/rc.log) failed: No such file or directory

### ISSUE THREAD

**Issue by eNTi** [OpenRC/openrc#216]
I've set in /etc/rc.conf:
```
rc_logger="YES"
rc_log_path="/var/log/rc.log"
```
but on init I get:
> openrc[1789]: Error: fopen(/run/openrc/rc.log) failed: No such file or directory

openrc 0.35.2-1 on Artix.

Help please?

**Comment by williamh** [comment]
Is /run mounted as a tmpfs?
What are the permissions on it?

**Comment by udeved** [comment]
I can answer that.

```
$ stat -c "%a %n" /run
755 /run
```
Does it require 1755?

**Comment by vapier** [comment]
we should aim for 755 perms on `/run` imo

**Comment by udeved** [comment]
@vapier 

https://github.com/OpenRC/openrc/blob/1edb5f6fd9c4827e5d4ed5c854bc322ba8a7df73/sh/init.sh.GNU.in#L25

init.sh creates a /run tmpfs with 755 if required.

It looks like my /run permissions match. Looking at rc-logger.c, could it be a tty race condition or something like that?

**Comment by udeved** [comment]
I just realized, isn't the mout command handing a wrong parameter?

` mount -t tmpfs -o mode=0755,nosuid,size=10% tmpfs /run `

nosuid instead of no-suid?

**Comment by vapier** [comment]
`nosuid` is correct

**Comment by dwfreed** [comment]
init.sh.GNU.in is only used when `uname -s` says `GNU` (which should only be Hurd).  According to http://git.savannah.gnu.org/cgit/hurd/hurd.git/tree/libdiskfs/opts-common.c, both `no-suid` and `nosuid` are acceptable, but somebody who actually knows/uses Hurd will have to confirm that.

Returning to the original question, does `/run/openrc/softlevel` exist during sysinit runlevel? (I would create a simple initscript that just does `cat /run/openrc/softlevel` and add it to the sysinit runlevel.  It should output `sysinit`)

**Comment by ryukinix** [comment]
@eNTi you solved that problem? I can replicate this issue for months (Artix's user as well), openrc 0.37.

**Comment by ryukinix** [comment]
~ ping ~

**Comment by dwfreed** [comment]
Can you answer the question I asked? Does `/run/openrc/softlevel` exist during sysinit runlevel?

**Comment by udeved** [comment]
@dwfreed 

i can answer, I just tested your suggestion.
```

$ cat /soft.log
sysinit
```
 
it does exist. I noticed this error occurred after I moved to a much faster nvme from older hdd.

**Comment by dwfreed** [comment]
The only thing I can think of is /run being in fstab, resulting in it getting mounted over, and thus losing the openrc directory.

**Comment by udeved** [comment]
If I look at the code https://github.com/OpenRC/openrc/blob/master/src/rc/rc-logger.c#L257
the fopen fails, which somehow leads me to think it has something to do with rc_logger_tty not being properly set. We do use openrc-init and supervised tty onartix, no initab.

**Comment by dwfreed** [comment]
rc_logger_tty is set by the openpty() call at the top of the function.  openpty() returns -1 on any failure, which would skip logging entirely.  I'm thinking you have /run listed in your fstab, which results in it getting mounted again, and so the /run/openrc directory wouldn't exist, so the logfile wouldn't be there.

**Comment by ryukinix** [comment]
![image](https://user-images.githubusercontent.com/7642878/52907937-831a0500-324a-11e9-8646-f23a2db0eb52.png)

Just to share... I know I'm not @udeved, but I don't have /run mounted in my fstab.

**Comment by dwfreed** [comment]
What is the content of `/proc/mounts`?

**Comment by ryukinix** [comment]
http://ix.io/1Bgr

**Comment by udeved** [comment]
@dwfreed 

I have never had any /run in fstab, never even had the idea to do that. 
Our default system also does not mount /run via fstab after installation.
I also checked our tmpfiles.d, there is no /run dir created, only subdirs.

**Comment by williamh** [comment]
@dwfreed  I am also seeing this; this is the issue I pinged you about on irc.

**Comment by williamh** [comment]
I would like to thank @floppym  for catching this. It looks like we are attempting to open the log before we have /run mounted.

**Comment by floppym** [comment]
Upon further review, `rc_logger_open()` seems to account for that by buffering output and attempting to open the temporary log later.

**Comment by dwfreed** [comment]
Is there anything special needed to replicate this? I installed artix with openrc as init and rc_logger is on.  Both with and without strace, I do not get any messages from openrc about failing to open /run/openrc/rc.log

**Comment by ryukinix** [comment]
I made a refresh install in july of 2018 (a updated artix iso) in other machine and I can't replicate this in that environment. However in my older machine (artix of 2017) I have this problem

**Comment by dwfreed** [comment]
Could you compare the /etc contents between the two?

**Comment by ryukinix** [comment]
Well... I tried exaustivly find a reason for that through /etc earlier, but I didn't find anything particular useful for debugging... I can share the file tree for both systems:

2017 Artix which has that problem: [/etc/](http://ix.io/1Bkw)
2018 Artix which don't has that problem: [/etc/](http://ix.io/1Bky)

If you are interested in some particular file I can send to you.

**Comment by udeved** [comment]
I have also 2 artix systems, a laptop with a pretty slow hdd, no error there, and my dev box with nvme throwing the fopen error.
Package selection on these system is almost identical, running plasma & sddm.

What I noticed on the nvme, I basically only see the error when I shutdown the system, ie the error message show relatively late in the boot process, after sddm started.

**Comment by williamh** [comment]
I see it on my home system when I switch to openrc-init, but not when I use sysvinit.

**Comment by udeved** [comment]
@williamh 

I installed today artix on a brand new ssd on a laptop that ran artix before on a slow hdd.
It had no error on hdd, and surprisingly, no error on the new ssd either.
All artix systems start with openrc-init.

**Comment by williamh** [comment]
@udeved  You have RC_LOGGER=yes in /etc/rc.conf correct (the default is no)?

**Comment by udeved** [comment]
@williamh 

Yes, we enable rc_logger by default.

**Comment by williamh** [comment]
Something is definitely going on still, because I just tested and still see the issue.

**Comment by udeved** [comment]
@williamh 

What I always wondered, the supervision guide for tty reads to put them in default, but doen't openrc require a tty much earlier?

**Comment by dwfreed** [comment]
OpenRC uses /dev/console for its messages, not /dev/ttyX

**Comment by udeved** [comment]
If I look at it, we know sysviinit is fine, and openrc-init produces the error.
What's different?
With openrc-init, tty start differently and eventually later, but, I just recalled, we packaged bootlogd from sysvinit standalone for use with runit.
Thought being, does sysvinit provide something via bootlod that openrc-init does not provide?

**Comment by zqqw** [comment]
The tmplog file is deleted by openrc when the default runlevel is reached, while rc-logger.c is between the fopen ae and fopen re lines.
Resulting message on my system with changes below to make the error message more verbose:
* Error: fopen(/run/openrc/rc.log) failed: No such file or directory ae1=1 ae2=0 ae3=1 level=default

```
diff -ura orig-openrc-0.40.3/src/rc/rc-logger.c new-openrc-0.40.3/src/rc/rc-logger.c
--- orig-openrc-0.40.3/src/rc/rc-logger.c	2018-12-21 18:24:18.000000000 +0000
+++ new-openrc-0.40.3/src/rc/rc-logger.c	2019-02-18 17:58:34.099205658 +0000
@@ -148,6 +148,11 @@
 	const char *logfile;
 	int log_error = 0;
 
+	int fopae1 = 0;
+	int fopae2 = 0;
+	int fopae3 = 0;
+
+
 	if (!rc_conf_yesno("rc_logger"))
 		return;
 
@@ -184,13 +189,15 @@
 		signal_pipe[1] = -1;
 
 		runlevel = level;
-		if ((log = fopen(TMPLOG, "ae")))
+		if ((log = fopen(TMPLOG, "ae"))) {
 			write_time(log, "started");
-		else {
+			fopae1 = 1;
+		} else {
 			free(logbuf);
 			logbuf_size = BUFSIZ * 10;
 			logbuf = xmalloc(sizeof (char) * logbuf_size);
 			logbuf_len = 0;
+			fopae1 = 9;
 		}
 
 		fd[0].fd = signal_pipe[0];
@@ -237,6 +244,9 @@
 			if ((log = fopen(TMPLOG, "ae"))) {
 				write_time(log, "started");
 				write_log(fileno(log), logbuf, logbuf_len);
+				fopae2 = 1;
+			} else {
+					fopae2 = 9;
 			}
 			free(logbuf);
 		}
@@ -255,6 +265,7 @@
 		}
 
 		if ((plog = fopen(logfile, "ae"))) {
+			fopae3 = 1;
 			if ((log = fopen(TMPLOG, "re"))) {
 				while ((bytes = fread(buffer, sizeof(*buffer), BUFSIZ, log)) > 0) {
 					if (fwrite(buffer, sizeof(*buffer), bytes, plog) < bytes) {
@@ -266,7 +277,7 @@
 				fclose(log);
 			} else {
 				log_error = 1;
-				eerror("Error: fopen(%s) failed: %s", TMPLOG, strerror(errno));
+				eerror("Error: fopen(%s) failed: %s ae1=%d ae2=%d ae3=%d level=%s", TMPLOG, strerror(errno), fopae1, fopae2, fopae3, level);
 			}
 
 			fclose(plog);

```

**Comment by zqqw** [comment]
Logging syscalls on the file with the 'audit' package revealed that openrc deletes the tmplog:
type=SYSCALL msg=audit(1550846417.100:77): arch=c000003e syscall=87 success=yes exit=0 a0=55f168b61a17 a1=7ffcee992fb9 a2=55f16a6b1c50 a3=2074612064657472 items=2
ppid=675 pid=677 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="openrc" exe="/usr/bin/openrc" key="runtmplog"

The failed open is not recorded as the OS seems to not make a kernel syscall when the file does not exist. Also the if tests are testing the assignment not the result of the fopen, although in this case it gives the right result, it's probably relying on undefined behaviour, so not good practice, unless it's intended as a performance optimization or something.
bootlogd uses an internal memory buffer while rc-logger uses a ramfs file to achieve the same result, saving messages before the fs is mounted.

**Comment by zqqw** [comment]
What is written to /dev/console appears on the tty it is connected to, usually /dev/tty1. So at boot you are looking at /dev/tty1 but it is showing messages written to /dev/console, but you can also write messages to /dev/tty1. They would not be logged by bootlogd as it logs what is written to /dev/console. rc-logger differs because it logs the messages directly from openrc that are going to be sent to /dev/console which is why some things you see on screen are not logged because they were written directly to /dev/console or /dev/tty1.

**Comment by dwfreed** [comment]
OpenRC removes the temp logfile at the end of every logging session, so that audit log on its own is useless.

`if((foo = bar(baz)))` is completely defined by the C standard, and is *very* commonly used.  The result of the if is the Boolean evaluation of the value of foo, which is set to the result of the bar function call.  For pointers, NULL evaluates to false, and any other value evaluates to true.  fopen returns NULL if it fails.

**Comment by zqqw** [comment]
It was bound to be some clever thing! Thank you for the explanation. But the times of the log seemed to show that openrc deleted it at the relevant time, and if you look for the file after having booted it is not there. The other point was I logged it by starting audit first in boot, then another time in sysinit, until I had booted to the desktop, and that was the only delete. Nobody else deleted it.
I used these audit rules:
-a always,exit -F arch=b32 -F path=/run/openrc/rc.log -S all -F key=runtmplog
-a always,exit -F arch=b64 -F path=/run/openrc/rc.log -S all -F key=runtmplog

My error message might not be the same as everyone elses and I suppose there is still room for other explanations.

**Comment by zqqw** [comment]
Looking at the code it seems rc-logger.c deletes the log at a point after the error message. So is it possible there could be a stopping 'boot' logger and a starting 'default' logger momentarily in existence together? But more investigation is needed I guess.

**Comment by williamh** [comment]
I am working on a patch for this. it looks like a possible synchronization issue between openrc-init and the openrc subprocesses that execute the runlevels.

**Comment by zqqw** [comment]
Testing the latest zip download shows this has fixed the issue for me, no error message is present now.
Thank you williamh for the patch, and to everyone else for helping to arrive at this point.
