### ISSUE TITLE
[question] Is there an equivalent of WorkingDirectory?

### ISSUE THREAD

**Issue by concatime** [OpenRC/openrc#218]
Hi.
I have a program that must be run from `/usr/local`. In systemd, there is `WorkingDirectory` as an option. Does OpenRC have something like this?

**Comment by williamh** [comment]
Yes, you can use the -d option for start-stop-daemon or supervise-daemon to change directories before starting the process. If you aren't using start-stop-daemon or supervise-daemon, just cd to the directory in the start() function in the script.

Let me know if that answers your question.

**Comment by concatime** [comment]
Ok, It works.
```openrc
#!/sbin/openrc-run
pidfile=run/webd.pid
start_pre() {
       checkpath --directory --owner root:www-data --mode 0710 srv
}
start() {
       supervise-daemon --pidfile $pidfile --chdir srv --start /srv/app --group www-data
}
```

Question aside, is there something like `start_stop_daemon_args` for `supervise-daemon`?
```
supervisor=supervise-daemon
start_stop_daemon_args='--group www-data --chdir /srv'
```

**Comment by williamh** [comment]
supervise_daemon_args is the supervise-daemon equivalent of start_stop_daemon_args.

Also, you should remove your start function and use the default, so set command and set supervisor to supervise-daemon.

Take a look at the openrc-run man page and supervise-daemon-guide.md in the distribution for more information.

**Comment by concatime** [comment]
Sorry for the silence. It works perfectly. Thank you again.

**Comment by igalic** [comment]
from what i'm reading in the man page, the `directory` option is supposed to do exactly this (but doesn't)

**Comment by mazunki** [comment]
Over three years have passed, I still had to add the following to my `init.d/user-server`

```openrc
directory="${SERVER_PATH}"
start_stop_daemon_args='--group mygroup --chdir $directory'
supervisor=supervise-daemon
```

Running OpenRC 0.44.5 on Gentoo.

**Comment by daef** [comment]
2023 - for me it seems like `directory` on its own is enough.

running openrc (OpenRC [LXC]) 0.47.1 on alpine 3.18

**Comment by Korenchkin** [comment]
latest news-solved it with this(maybe not ideal,but works):
```
#!/sbin/openrc-run

name="zoraxy"
supervisor="supervise-daemon"
#directory="/opt/zoraxy"
command="./zoraxy_linux_amd64"
command_args="-port=:8000"
pidfile="/run/$SVCNAME.pid"

depend() {
        need net
        use dns
}

start_pre()
{
        cd /opt/zoraxy
}

```

**Comment by Redplcs** [comment]
hello from 2025. seems like directory worked?? i have lxc container with alpine running traefik through community scripts

this is my service file:
```
#!/sbin/openrc-run
supervisor=supervise-daemon

name="Traefik"
description="Modern reverse proxy and load balancer"
directory=/etc/traefik

command="/usr/sbin/traefik"
command_args="$traefik_opts"
command_user="traefik:traefik"
capabilities="^cap_net_bind_service"

description_healthcheck="Check health status by calling /ping endpoint"
healthcheck_timer=30

depend() {
        need net
        after firewall
}

healthcheck() {
        $command healthcheck >/dev/null
}

start_pre() {
        checkpath -d -m 0775 -o $command_user /var/log/traefik
}
```

**Comment by liam-bh** [comment]
Worked for me too! Thanks for posting that example Redplcs

**Comment by 8ebb82** [comment]
This issue helped me a lot. Just set the value of `directory` and it will work fine. Thanks.
