### ISSUE TITLE
[openrc-shutdown] support delayed/scheduled times (akin to `shutdown +60`)

### ISSUE THREAD

**Issue by artixmaniac** [OpenRC/openrc#221]
Delayed or scheduled shutdown not implemented yet - would be great! Thanks

**Comment by williamh** [comment]
Do we need the '+' notation?
I'm working on this now and right now what I have is, if you use hh:mm it is an exact time, but if you use just a number it means delay that many minutes.

**Comment by williamh** [comment]
This has been implemented in 0.39.x, and we do use the '+' option.
