### ISSUE TITLE
How to stop/restart service after the service process crashed

### ISSUE THREAD

**Issue by tclh123** [OpenRC/openrc#235]
If the service process crashed or killed by others. The openrc status of the service is still "started". But the process is not exist, and the pid file can't be find. If I try to stop or restart the service via openrc, it will fail. I can write a dummy stop function in the service init.d script, to do a fake stop and fix the openrc status. But it is too awful.

```
$ sudo /etc/init.d/unscd status
 * status: started
$ sudo /etc/init.d/unscd stop
 * Caching service dependencies ...                                                                                                                                                                                             [ ok ]
 * Stopping Name Service Cache Daemon (unscd) ...
 * Failed to stop Name Service Cache Daemon (unscd)                                                                                                                                                                             [ !! ]
 * ERROR: unscd failed to stop
$ ls /run/nscd/nscd.pid
ls: cannot access /run/nscd/nscd.pid: No such file or directory
```

**Comment by cdlscpmv** [comment]
I guess you should try `rc-service <service> zap` before starting it again.

**Comment by tclh123** [comment]
@cdlscpmv Thanks. I don't know there's such a special command to reset a crashed service to stopped state before.
