### ISSUE TITLE
Interactive mode should work even if rc_parallel is enabled

### ISSUE THREAD

**Issue by l29ah** [OpenRC/openrc#24]
They're explicitly incompatible atm so one has to provide a way to log in around openrc to fix boot problems if one is to use the parallel boot mode.

**Comment by williamh** [comment]
I will enable this in 0.22 with the caveat that I do not know why it was disabled. It was disabled in the past with no explanation.

**Comment by l29ah** [comment]
On Mon, Sep 19, 2016 at 10:05:49AM -0700, William wrote:
> I will enable this in 0.22 with the caveat that I do not know why it was disabled. It was disabled in the past with no explanation.

Have you checked if it actually works this way? I vaguely remember it was ignoring the key.

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments
