### ISSUE TITLE
Segmentation fault when running `rc-update add x boot` in chroot on Alpine Linux

### ISSUE THREAD

**Issue by Fusl** [OpenRC/openrc#243]
When running `rc-update add $service boot` in a chroot on Alpine Linux installer, the command segfaults. It does not segfault when running `rc-update add $service default` and I pinpointed this to [line 1073 and 1074 of the librc.c file](https://github.com/OpenRC/openrc/blob/7cb8d943236fe651ac54c64f8167f7c4369f649c/src/librc/librc.c#L1073). When commenting these lines out, adding services to the boot runlevel works just fine.

**Comment by mcassaniti** [comment]
I assume this one can now be closed?
