### ISSUE TITLE
removing the authors file

### ISSUE THREAD

**Issue by williamh** [OpenRC/openrc#249]
Hey all,

Git does a much better job of tracking who the authors of OpenRC are than the authors file does, and legally I don't believe we are required to have an authors file. 

I would like to remove this file in a release or two if there are no objections.

**Comment by vapier** [comment]
the license says "Copyright (c) 2007-2015, the OpenRC authors".  there is no legal entity named "the OpenRC authors", so the AUTHORS file lists the legal entities (i.e. people).

should be easy to autogenerate it from git history.

**Comment by williamh** [comment]
Why do we need to generate it at all though since this information can be retrieved by anyone who wants it from git history?
