### ISSUE TITLE
shutdown delay with version 0.39.1

### ISSUE THREAD

**Issue by cimarronline** [OpenRC/openrc#250]
Since updating to version 0.39.1, `openrc-shutdown -r`(or`-p`)`now` seems to do nothing for about 30 seconds before rebooting (or shutting down) normally. Version 0.38.3 shuts down without any delay.

I enabled verbose logging but see nothing unusual, no apparent difference in rc.log between versions 0.38.3 and 0.39.1, besides taking about 30 seconds longer. 

EDIT: I managed to figure out how to revert commits and it's the [health checks commit](https://github.com/OpenRC/openrc/commit/c1e582586d398b4452f568240985247294f645ef) that's causing my delay.

EDIT: I further narrowed it down to this section of the health checks commit: `@@ -488,46 +505,88 @@ static void supervisor(char *exec, char **argv)`

**Comment by williamh** [comment]
Hi, can you please test openrc-0.39.2 which was just released and let me know here if the issue still exists?

Thanks,

William

**Comment by udeved** [comment]
Just updated openrc 0.39.2 in our testing repo, I still get a defunct shutdown on two test systems.
It seems the -p arg demands a time specified. The old sysvinit option "now" is not implemented, and it only seems to accept integers.

```
sudo openrc-shutdown -p
 * openrc-shutdown: No shutdown time specified
```

If I try to shutdown from plasma, I will be returned to the sddm screen, but no shutdown, even after waiting a minute.

**Comment by cimarronline** [comment]
Yes, 0.39.2 reboots and shuts down for me without delay. Thank you! I do need to specify a shutdown time, but "now" works for me.

**Comment by udeved** [comment]
I think the issue should be either reopened or a new ticket is required.

Shutting down from terminal works, but eg plasma with sddm doesn't.
I suspect the time requirement for -p arg to be reason, because 0.38.x properly shuts down without a time specified.

**Comment by cimarronline** [comment]
I see the same failure to reboot or shutdown with lightdm, but I think it's a separate issue. Shutdowns from the greeter work if I change the exec line in the shutdown commands in /usr/lib/openrc/bin:

from `exec /usr/bin/openrc-shutdown ${option_arg} ${poweroff_arg} "$@"`
to `exec /usr/bin/openrc-shutdown ${option_arg} ${poweroff_arg} "now"`

It seems to me these scripts should default to "now" if no time is specified.

**Comment by williamh** [comment]
The time argument is mandatory, so yes those scripts need to be fixed. That's a separate issue though, and I'll take care of it in another release today.

**Comment by williamh** [comment]
Thinking about it though, sysvinit shutdown never assumed anything about the default time either, so I'm not sure we want to have a default of "now" on shutdown.

**Comment by udeved** [comment]
In my opinion, 0.39.x should behave like 0.38.x, where `openrc-shutdown -p` just works.
