### ISSUE TITLE
use of _GNU_SOURCE should be avoided

### ISSUE THREAD

**Issue by williamh** [OpenRC/openrc#262]
If it is possible, I would rather avoid using _GNU_SOURCE. this opens up the code to portability issues since we run on operating systems and c libraries which do not support it.

Thoughts?

**Comment by atlaua** [comment]
I concur. While defining _GNU_SOURCE is not a portability issue in itself, it makes it easier to inadvertenyly introduce other portability issues in  the future.

**Comment by vapier** [comment]
i don't think this is a valid reason to revert that O_PATH handling.  the commit didn't break on any system as all usage was properly gated.  i get the desire to not dump `_GNU_SOURCE` everywhere to try and avoid accidental standard deviation, but that's not what happened.

if you really want to make sure openrc keeps building for different systems, then there is no replacement for actually building & testing on those systems (i.e. a CI like Travis).  add coverage to that script and you're done.

**Comment by williamh** [comment]
@vapier wrt the O_PATH handling, we can look at it again after 0.40 is out, which should happen tomorrow. If we bring something like it back, it needs some other changes. Also, Travis doesn't support *bsd, so I don't really have a way to build there at this point.

**Comment by vapier** [comment]
last i looked, cross-compilers work

**Comment by vapier** [comment]
looks like this was fixed in b6fef599bf8493480664b766040fa9b0d4b1e335 for #201
