### ISSUE TITLE
BSD make can't build openrc

### ISSUE THREAD

**Issue by gyakovlev** [OpenRC/openrc#266]
as discussed here https://github.com/OpenRC/openrc/pull/265#discussion_r239338063
bsd make can't build openrc, gmake is a requirement.

from the fist glance `TOP:=` assignement seems to end up empty thus we are getting / prefix for path to additional mk and Makefile.inc files.

**Comment by williamh** [comment]
That is correct, gmake is a requirement and is available on *bsd as far as I know.

**Comment by williamh** [comment]
Once I feel it is ready to go, I want to switch over to a meson based build for OpenRC, so we will need meson and ninja to build it. It looks like both of these are on *BSD as well.

**Comment by austin987** [comment]
FYI, GNU Make requirement is listed in the README.

**Comment by vapier** [comment]
my mistake ... we used to support BSD make, but i guess we gave up on it
