### ISSUE TITLE
tests use gnu sed extensions

### ISSUE THREAD

**Issue by gyakovlev** [OpenRC/openrc#267]
as a result bsd sed can't be used to run tests.

details here https://github.com/OpenRC/openrc/pull/265#discussion_r239345650

gnu sed
```
q [exit-code]
              Immediately quit the sed script without processing any more input, except that if auto-print is not disabled the current pattern space will be printed.  The exit code argument is a GNU extension.
```

bsd sed
```
[1addr]q
	     Branch to the end of the script and quit without starting a new
	     cycle.
```
the line is
https://github.com/OpenRC/openrc/blob/9dae4f2e38ceae227933673e25db9583e8f610a6/src/test/runtests.sh#L88-L91

**Comment by williamh** [comment]
@gyakovlev  Is this still an issue?

**Comment by gyakovlev** [comment]
still an issue, but since you've removed most of the offending tests, I was able to find only single leftover.

test/runtests.sh line 42
https://github.com/OpenRC/openrc/blob/44f5a72d1aeb131cc2cb464a53809a5a8d90c46e/test/runtests.sh#L42

**Comment by vapier** [comment]
i believe this is resolved now after migrating to meson
