### ISSUE TITLE
devfs inside lxd container doesn't mount /dev/shm

### ISSUE THREAD

**Issue by palica** [OpenRC/openrc#272]
I am mounting /dev/shm manually via profile with:

`raw.lxc: lxc.mount.entry = none dev/shm tmpfs rw,nosuid,nodev,noexec,create=dir`

as a workaround inside containers, because /etc/init.d/devfs is -lxc keyworded. 

When removing the `-lxc` I can boot the container without any issues and also the /dev/shm gets mounted correctly. I don't know what is the reason not to run devfs inside container. Can this be considered and possibly fixed?

There is no difference between mounts in a container using profile and container using modified devfs with removed -lxc keyword.

Thank you

**Comment by kr0k0** [comment]
Why is this issue ignored? The missing devfs in lxc/lxd containers is really annoying.

The easiest solution would be to remove the "-lxc" in devfs, but is this what you want?

**Comment by floppym** [comment]
It would be a terrible idea security-wise to mount devtmpfs in the container.

I'm not familiar with lxc, but systemd-nspawn takes care of mounting a new tmpfs instance on /dev, populating basic device nodes, and mounts another tmpfs at /dev/shm. OpenRC doesn't need to to do any of that.

Does lxc have some config option that would do this?

**Comment by floppym** [comment]
Reported on Gentoo as [bug 761918](https://bugs.gentoo.org/761918).
