### ISSUE TITLE
Support automatic multiseat creation

### ISSUE THREAD

**Issue by ezst036** [OpenRC/openrc#282]
Please add support for accepting a command issued either to bash or issued from a GUI which handles the creation of multiseat systems using either multiple video cards, external USB video components, or single video card with multiple outputs.

Any udev, xorg, wayland, or other configuration necessary to establish multiseat and assign devices to various seats should be a transparent process handled by OpenRC.

**Comment by LW-archlinux** [comment]
I do think that kind of functionality doesn't belong in an init system .
Have you looked at consolekit2 or elogind ?

https://github.com/ConsoleKit2/ConsoleKit2
https://github.com/elogind/elogind

**Comment by vapier** [comment]
or use systemd instead.  seems like multiseat creation is a non-goal for openrc.  maybe William feels differently.

**Comment by williamh** [comment]
I don't know much about the whole multi-seat thing, but I think elogind does this for non systemd systems [1]. Again, I don't know, so please educate me. :-)

[1] https://github.com/elogind/elogind

**Comment by cromerc** [comment]
@williamh Yes elogind handles this for non systemd systems, and works with both OpenRC just fine. It is what we use in Artix Linux.

Just to voice my opinion. OpenRC should not be responsible for this, it is beyond the scope of the project which is to handle init and services, and would go against the unix philosophy of do just 1 thing and do it well.

**Comment by williamh** [comment]
This seems to be handled by elogind or consolekit2, and out of scope for OpenRC.
