### ISSUE TITLE
crashed services with version 0.41

### ISSUE THREAD

**Issue by cimarronline** [OpenRC/openrc#297]
With version 0.41 I'm seeing several services listed as crashed (acpid, cupsd, and udev). The daemons are running. Restarting the service shows no errors:
```
rc-service cupsd restart
 * Executing: /usr/lib/openrc/sh/openrc-run.sh /usr/lib/openrc/sh/openrc-run.sh /etc/init.d/cupsd stop
 * Stopping cupsd ...
 * Will stop /usr/bin/cupsd
 * Will stop processes of `/usr/bin/cupsd'
 * start-stop-daemon: no matching processes found                                                                                       [ ok ]
 * Executing: /usr/lib/openrc/sh/openrc-run.sh /usr/lib/openrc/sh/openrc-run.sh /etc/init.d/cupsd start
 * Starting cupsd ...
 * Detaching to start `/usr/bin/cupsd' ...   
```
But the service still crashes. These services ran fine with version 0.40.3.

The only other thing I noticed in rc.log is several instances of "No such file or directory" for pid files, but these services are not the crashed ones. Like this:
```
* Executing: /usr/lib/openrc/sh/openrc-run.sh /usr/lib/openrc/sh/openrc-run.sh /etc/init.d/cronie start
 * Starting cronie ...
 * start-stop-daemon: fopen `/run/crond.pid': No such file or directory
 * Detaching to start `/usr/bin/crond' ...
 [ ok ]
```
When I check in /run after startup, the pid files are where they are supposed to be, and the respective services are running.

**Comment by Masanetz** [comment]
Going back to 0.40.3 magically fixes the crashed services without restarting them...
It looks like the checks for running processes is somewhat broken...

**Comment by williamh** [comment]
Here is a tarball which will be available for 14 days that contains all of the patches that go from 0.40.3 to 0.41.

https://transfer.sh/6JUbi/openrc-0.41-patches.tar.gz

We need to find out which patch broke the services status.

Basically, go back to 0.40.3, apply these patches until it breaks, then let me know which patch breaks things.

Thanks,

William

**Comment by eseifert** [comment]
Applying the patches up to (and including) `0016-src-librc-librc-daemon.c-fix-buffer-overrun-in-pid_i.patch` causes the services’ status to be  `crashed`

**Comment by Masanetz** [comment]
Applying only `0016-src-librc-librc-daemon.c-fix-buffer-overrun-in-pid_i.patch` causes the services’ status to be `crashed`, too.

**Comment by cimarronline** [comment]
Yes, I just tried reverting `0016-src-librc-librc-daemon.c-fix-buffer-overrun-in-pid_i.patch` and no more crashed services.
