### ISSUE TITLE
hwclock: support for s390x

### ISSUE THREAD

**Issue by tuan-hoang1** [OpenRC/openrc#306]
Hello OpenRC team,

I am trying to get clock support for s390x platform at : https://github.com/alpinelinux/aports/pull/6632.

This runs mostly on QEMU/KVM environment. For z/VM I think s390x has to go with swclock.

The gettod.c file is from qemu project: 
qemu/include/qemu/timer.h
qemu/target/s390x/s390-tod.h

Thanks.

**Comment by williamh** [comment]
Hi, I looked at the Alpine PR you linked, and it would be better if you could open a PR against our repository instead of just an issue.
That way we can make sure it builds with our CI, etc.

Thanks much,

William

**Comment by tuan-hoang1** [comment]
Hi William @williamh,

My patch is more like a proposal, I still don't have a final patch yet for openrc.

I was using swclock on s390x and it does not work. hwclock returns immediate on s390x without doing anything. But I still get the correct time after each reboot with both of them disabled (*).

As far as I know on s390x, correct way to get time is to call gettimeofday(), kernel will get the time from the hypervisor (be it KVM or z/VM) through its clock source driver called 'tod'.

Looking at openrc source, I don't see where gettimeofday() is called to set the time. I just figured out (*) today. So if you don't have further comment, I would like we just close this issue as I will disable both clock on Alpine s390x.

Many thanks,
Tuan

**Comment by tuan-hoang1** [comment]
Or maybe just use hwclock since it's harmless :)
