### ISSUE TITLE
openrc-0.41.2 randoomly crashes during boot

### ISSUE THREAD

**Issue by stefson** [OpenRC/openrc#309]
I'm a gentoo user, and openrc-0.41.2 was marked as stable a few days ago. So I upgraded from 0.38.3, and since then there is in 1/10 cases a reboot during the boot of openrc. The monitor turns off, and on again and voilá, my pc has rebooted. 

Initially I thought of a kernel problem, so I downgraded from 4.14.116 back to v114 before the openrc update, but to no avail, it happened again. 

So, my most important question is: how can I pin this down further? rc logging is active, should I add the log here?

**Comment by williamh** [comment]
I would need a copy of rc.log when it happens.

I have no idea off the top of my head what would cause a monitor to turn 
off and cause a system to reboot like that.


Thanks,


William

**Comment by stefson** [comment]
thanks for the fast reaction, here is my log: [rc.log.gz](https://github.com/OpenRC/openrc/files/3145210/rc.log.gz)
new openrc is emerged as of:
```
     Thu May  2 21:08:12 2019 >>> sys-apps/openrc-0.41.2
       merge time: 27 seconds.
```

**Comment by stefson** [comment]
and my kernel config, might be helpfull? [kernel-4.14.114-config.gz](https://github.com/OpenRC/openrc/files/3145213/kernel-4.14.114-config.gz)

**Comment by williamh** [comment]
I looked through several reboots at the end of the log, and there are no 
obvious errors, OpenRC appears to be rebooting your system as it should.


- Do you have rc_parallel turned on? If you do, turn it off and let me 
know if that fixes the issue.


- what is a ryzen kernel? Is that a custom kernel of some kind? (I can't 
find it in Gentoo)


William

**Comment by williamh** [comment]
Another thing I would like to see is the output from rc-status --all. Please run this command and attach rc-status.txt:

```
# rc-status --all >& rc-status.txt
```

Thanks,

William

**Comment by stefson** [comment]
I did use parallel boot in the past, but refrained from it as I once ended up in a deadlock. The kernel is built from gentoo-sources, it's just a little nick given by me to reflect it's config is able to boot ryzen :)

[rcconf+rc-status.zip](https://github.com/OpenRC/openrc/files/3145816/rcconf%2Brc-status.zip)

**Comment by stefson** [comment]
my harddisk crashed 10 last week, hasn't happened again since.
