### ISSUE TITLE
localmount fails with aufs at shutdown

### ISSUE THREAD

**Issue by udeved** [OpenRC/openrc#31]
I am using aufs on manjaro, and aufs leaves a config file in /sys/fs/aufs with the kernel config.
Thus, localmount fails at shutdown, because it doesn't do a directory test.

Something like this should prevent the umounting triggered if a file is present.

    for aufs_si_dir in /sys/fs/aufs/*; do
			if [[ -d $aufs_si_dir ]];then
			    aufs_mount_dir=${aufs_si_dir#/sys/fs/aufs/}
			    aufs_si_id="$(printf "%s" $aufs_mount_dir | sed 's/_/=/g')"
			    aufs_mount_point="$(mountinfo -o ${aufs_si_id})"
			    for x in $aufs_si_dir/br[000-999]; do
				    aufs_branch=$(sed 's/=.*//g' $x)
				    eindent
				    if ! mount -o "remount,del:$aufs_branch" "$aufs_mount_point" > /dev/null 2>&1; then
					    ewarn "Failed to remove branch $aufs_branch from aufs \
						    $aufs_mount_point"
				    fi
				    eoutdent
				    sync
			    done
			fi
		done

**Comment by dwfreed** [comment]
This has been implemented
