### ISSUE TITLE
rc_crashed_start is not working

### ISSUE THREAD

**Issue by martincmelik** [OpenRC/openrc#32]
Hi,

I hope I get it right. When stated in /etc/rc.conf
rc_crashed_start=YES
then OpenRC should try to bring up services which crashed, right?
I set this variable, reboot, then verify that vixie-cron is running, kill vixie-cron PID, rc-status showed me that vixie-cron is in "crashed" state, but even after 30 minutes, it does not try to restart the service...

I have latest stable Gentoo (amd64) with latest stable OpenRC.

Thank you

**Comment by rindeal** [comment]
can be closed as invalid
