### ISSUE TITLE
/lib/rc/sh/rc-cgroup.sh: line 80: echo: write error: Invalid argument

### ISSUE THREAD

**Issue by James-TR** [OpenRC/openrc#33]
I get errors every time I do anything with services :/
```
/lib/rc/sh/rc-cgroup.sh: line 80: echo: write error: Invalid argument
/lib/rc/sh/rc-cgroup.sh: line 87: echo: write error: Invalid argument
```

**Comment by qnikst** [comment]
What openrc version do you use?

**Comment by James-TR** [comment]
currently on 0.13.1. running under musl with grsec, as well

**Comment by James-TR** [comment]
0.13.7 does the same (but the line numbers are changed)

**Comment by nwmcsween** [comment]
This is a bug in the kernel wrt to posix standards, an easy fix is to use echo -n in place of echo

**Comment by williamh** [comment]
I would rather use printf if that is possible; echo -n is not posix.
Would printf work?

**Comment by nwmcsween** [comment]
printf works
