### ISSUE TITLE
[question] Is it possible to run my script as PID 1 using openrc

### ISSUE THREAD

**Issue by KarthikNedunchezhiyan** [OpenRC/openrc#358]
Is it possible to run my custom script as PID 1 using openRC?

**Comment by cromerc** [comment]
Yes, you must name save your script in "/sbin/init" and in your script you need to call openrc to run it as a service manager.

**Comment by KarthikNedunchezhiyan** [comment]
ohh nice, what is the role of `service manager`?

**Comment by cromerc** [comment]
OpenRC is a service manager. It starts, restarts, stops, and monitors service daemons.

**Comment by KarthikNedunchezhiyan** [comment]
cool 👍
