### ISSUE TITLE
virsh console (libvirt) & OpenRC : impossible to get login prompt

### ISSUE THREAD

**Issue by 2Belette** [OpenRC/openrc#367]
Using libvirt, and specifically `virsh console` command to retrieve virtual machine console.

If I am adding "console=ttyS0" in my GRUB_CMDLINE_LINUX, I can see the OpenRC init : 

```
Starting sysinit runlevel

   OpenRC 0.28 is starting up...
[...]
 * Starting sshd ...
 [ ok ]
```

and nothing else ! 
It seems that OpenRC respawn on tty1 and this is the behavior when accessing the VM through VNC but I can't find a way to get the login prompt from `virsh console` ...

Is there an option to launch the login prompt on the same ttyS0 and avoid a respawn into another tty ? Or any other tips ?

Many thanks

**Comment by gyakovlev** [comment]
unlike systemd, openrc will not launch getty by default. you have to turn it on.

if you use sysvinit (default configuration) - you have to enable `ttyS0` console in `/etc/inittab`

for example
```inittab
s0:12345:respawn:/sbin/agetty -L 115200 ttyS0 vt100
```

if you use openrc-init, you have to create  a symlink and enable service
```sh
cd /etc/init.d
ln -s agetty agetty.ttyS0
rc-update add agetty.ttyS0 default
```

**Comment by williamh** [comment]
I don't think there is anything for me to do here given the previous comment, so I am closing this. Please ping the issue again if you disagree. Thanks much. :-)
