### ISSUE TITLE
openrc-init shutdown signal

### ISSUE THREAD

**Issue by cromerc** [OpenRC/openrc#370]
I am working on running openrc-init inside of a docker image. It works well and launches services fine. But there is one problem. openrc-init does not handle a signal to shutdown. This causes a problem when I run "docker stop service" because it just ends up killing pid 1 without shutting down the running services properly.

As can be seen here:
https://github.com/OpenRC/openrc/blob/master/src/rc/openrc-init.c#L207
SIGINT is handled, but this does a reboot. What is needed is a signal to handle shutdown. I would be happy to open a pull request to do this, but I don't know what signal I should choose to listen for.

**Comment by nervo** [comment]
https://github.com/OpenRC/openrc/pull/398 ?

**Comment by cromerc** [comment]
Yes, this will fix it.
