### ISSUE TITLE
Remove (useless) ChangeLog

### ISSUE THREAD

**Issue by tokiclover** [OpenRC/openrc#38]
Please remove the *useless* ChangeLog (nobody wants a plain commit list when anybody have access to that said list), or else, add a *proper* ChangeLog (which highlights noticeable change between version bumps.)

The current format--commit list--does not satisfy anybody, does it? I mean those who want a ChangeLog but have no use of the current format. Morever, the current format is too big and just conflate the tarball for no purpose at all... but confuse the users that want one--I am one of them.

End result: I am now boycoting, for a few months, newer OpenRC versions if I don't have the time to take care of it to not end up... with unbootable system with bad surprise(s).

Thanks.

**Comment by williamh** [comment]
@tokiclover:
@whissi contributed the code, so at least one person does find it useful; you might want to chat with him about it. Also, this  seems to be an extremely trivial reason to "boycott" future updates of OpenRC.

**Comment by Whissi** [comment]
Like @williamh already said, I was the one who requested to ship a ChangeLog with OpenRC.

**Why I requested a ChangeLog in summary:**
* As user I want to know *why* there was an update.
* If anything I use will be broken after an update, I will be able to know where to start looking. For example if your runscripts depends on "foo" but OpenRC won’t provide "foo" anymore with the latest version, a ChangeLog will tell you at least where to start to find a solution.
* Going online to read about changes isn’t possible all the time.

I agree with you that the current format isn’t very user-friendly. I would prefer a handwritten NEWS file focused on users (not developers who can read the commit log). But this is a trade-off with having at least some information vs. developers who don’t want to spend time in writing a NEWS file in times where they already took care of writing good commit messages.

**Comment by tokiclover** [comment]
Well then, closing this.
