### ISSUE TITLE
start-stop-daemon.sh incorrect usage of --user

### ISSUE THREAD

**Issue by ChibaPet** [OpenRC/openrc#383]
start-stop-daemon.sh uses --user when it really wants --chuid, when calling
the start-stop-daemon utility. The result of this is that command_user does 
nothing.

The line:

    ${command_user+--user} $command_user \

ought to instead be:

    ${command_user+--chuid} $command_user \

**Comment by gyakovlev** [comment]
Don't think it's correct conclusion.

`--chuid` does exactly what `--user` does + prints a warning in fallthru that it's deprecated.
https://github.com/OpenRC/openrc/blob/2355f1a3f2a4fd62cac6d9af0e94c8731acd4c0f/src/rc/start-stop-daemon.c#L386-L390

Same information clarified in manpage.
https://github.com/OpenRC/openrc/blob/2355f1a3f2a4fd62cac6d9af0e94c8731acd4c0f/man/start-stop-daemon.8#L108-L110

**Comment by ChibaPet** [comment]
Oh, interesting. So, in Debian and Devuan, start-stop-daemon comes from dpkg, and --user and --chuid are distinctly different:

[https://git.dpkg.org/cgit/dpkg/dpkg.git/tree/utils/start-stop-daemon.c](https://git.dpkg.org/cgit/dpkg/dpkg.git/tree/utils/start-stop-daemon.c)

Here's the code from there:

```
		case 'u':  /* --user <username>|<uid> */
			match_mode |= MATCH_USER;
			userspec = optarg;
			break;
		case 'v':  /* --verbose */
			quietmode = -1;
			break;
		case 'x':  /* --exec <executable> */
			match_mode |= MATCH_EXEC;
			execname = optarg;
			break;
		case 'c':  /* --chuid <username>|<uid> */
			free(changeuser);
			/* We copy the string just in case we need the
			 * argument later. */
			changeuser_len = strcspn(optarg, ":");
			changeuser = xstrndup(optarg, changeuser_len);
			if (optarg[changeuser_len] == ':') {
				if (optarg[changeuser_len + 1] == '\0')
					fatal("missing group name");
				changegroup = optarg + changeuser_len + 1;
			}
			break;
```
I guess start-stop-daemon.sh needs to be aware of which start-stop-daemon 
it's calling, as on Debian and Devuan command_user is definitely broken.

**Comment by gyakovlev** [comment]
It's a bit unexpected that on de*an it uses different implementation.
I see openrc's implementation being removed in `override_dh_installmenu:` in the `rules` file.

If memory serves me well openrc on de*an manages both sysvinit '#!/bin/sh` scripts and `openrc-run` scripts, right?
Yeah, in that case it may need some extra logic. looking at debian patches it actually does support both.
https://sources.debian.org/patches/openrc/0.42-1/

It really looks like packaging overlook and downstream patch candidate to me, but I'm not a maintainer, just helping here sometimes and decided to dig a bit.

fun fact: it behaved like this at least 13 years:

https://github.com/OpenRC/openrc/commit/d1a1e3a3c9ddbb8cb1528747c68581ecd582d49f#diff-13a9c36b3606fedc057e8b80dd7677e8459bcbe2a35b23a73592071e8fbaadf0

https://github.com/OpenRC/openrc/commit/bc90e41b76b3cfd44da55e4f4da8bbe9d82f5969#diff-13a9c36b3606fedc057e8b80dd7677e8459bcbe2a35b23a73592071e8fbaadf0

**Comment by ChibaPet** [comment]
Alright, yeah, you're clearly correct. I hadn't looked at the bigger picture when I opened this, and didn't realize that OpenRC shipped its own start-stop-daemon. I don't believe Devuan forks OpenRC, so probably the best place to note it is the Debian BTS. I'll see about filing a bug there.

Thank you for the clarification. I'll close this now.
