### ISSUE TITLE
New release request

### ISSUE THREAD

**Issue by andrey-utkin** [OpenRC/openrc#393]
I have previously raised the same request on Gentoo bugtracker: https://bugs.gentoo.org/759034 .
There was no response since. Unfortunately it's unclear which of the bugtrackers is the official one. So I'm raising it there as well.

It's been more than a year, and 3265 commits, since last OpenRC release 0.42.1: https://github.com/OpenRC/openrc/tags
Please issue a new one soon.
There's one bugfix committed, but not released, which I care about: https://bugs.gentoo.org/755422

**Comment by realkinetix** [comment]
Yes, please release!

**Comment by akhuettel** [comment]
I'll poke williamh with something pointy.

**Comment by williamh** [comment]
OpenRC 0.43 is out.
