### ISSUE TITLE
[Question] is newnet a thing?

### ISSUE THREAD

**Issue by ngortheone** [OpenRC/openrc#395]
Various wikis[1] suggest that OpenRC has "newnet" way of configuring network. But there is hardly any evidence that `newnet` thing exists. Most of the information that can be found is dated 2012, which is almost 9 years old as of date. 

So the question is to clarify the status of the feature.

1. Various wikis: 
https://wiki.gentoo.org/wiki/Network_management
https://wiki.archlinux.org/index.php/OpenRC

**Comment by cromerc** [comment]
The code is there, so yes it does exist. But not every distro that uses openrc has it available. For example in Artix Linux we disable it.
