### ISSUE TITLE
cgroup cleanup hangs waiting for its own subshell

### ISSUE THREAD

**Issue by matthew-sharp** [OpenRC/openrc#396]
I'm consistently getting hangs while stopping services with cgroup cleanup enabled. Through debugging I have determined that cgroup_get_pids() finds 2 pids each iteration of the loop. One is the parent openrc shell ($$) and the other is the subshell that cgroup_get_pids() is running in due to process substitution. This means that cgroup_cleanup() spins until the timeout as cgroup_get_pids() always returns a pid.

Replacing cgroup_get_pids() with this fixes the issue:
```bash
cgroup_get_pids()
{
        local cgroup_procs p pids self
        cgroup_procs="$(cgroup2_find_path)"
        read -r self _ < /proc/self/stat
        [ -n "${cgroup_procs}" ] &&
                cgroup_procs="${cgroup_procs}/${RC_SVCNAME}/cgroup.procs" ||
                cgroup_procs="/sys/fs/cgroup/openrc/${RC_SVCNAME}/tasks"
        [ -f "${cgroup_procs}" ] || return 0
        while read -r p; do
                [ "$p" -eq $$ ] || [ "$p" -eq "$self" ] || pids="${pids} ${p}"
        done < "${cgroup_procs}"
        printf "%s" "${pids}"
        return 0
}
```

I'll try to get a proper PR up soon.

**Comment by williamh** [comment]
@matthew-sharp  Can you take a look at #409 and let me know what you think about it?
It might be better to use something like that and avoid process substitution in this case.

Thanks,

William

**Comment by matthew-sharp** [comment]
Sure. I had a look and think your PR is the better fix.
