### ISSUE TITLE
Init script in 'default' hangs boot, unable to bypass

### ISSUE THREAD

**Issue by lyssieth** [OpenRC/openrc#404]
I mistakenly left the wrong version of an init script active, and it is freezing the process of starting everything up. The drive is encrypted so I can't just mount it from a live usb and delete the file, is there some solution using openrc or grub to maybe try and bypass this?

I'm sorry if this is the wrong place. My Google-Fu abilities ran dry, I'm tired, and  I want my machine back.

**Comment by lyssieth** [comment]
Adding some information now that I'm awake:
- Latest version of OpenRC
- Artix Linux
- ZFS Root

**Comment by cromerc** [comment]
Boot with a usb flash drive that has a linux distro on it. Mount the partition, fix your problem unmount and reboot.

**Comment by cromerc** [comment]
You can mount it from a live usb. You can decrypt it once you have the live usb running, then mount it.

**Comment by lyssieth** [comment]
I've tried that. I can't figure out how to decrypt it since ZFS claims "key not loaded" or something like that. I don't exactly remember, since I've slept. I'll try again and bring more accurate messages in a bit, once I wake up more.

**Comment by lyssieth** [comment]
Okay, I've figured it out, zfs commands were just being fucky yesterday (or I was tired). I now gotta figure out how to mount it to where I can actually edit it.

**Comment by lyssieth** [comment]
The only directories I've been able to mount are:
- `/home`
- `/opt`
- `/root`
- `/srv`
- `/usr`
- `/var`

I can't seem to get `/etc` accessible to me yet.
The system is configured based on [this guide](https://openzfs.github.io/openzfs-docs/Getting%20Started/Arch%20Linux/Artix%20Linux%20Root%20on%20ZFS.html), if that helps.

**Comment by lyssieth** [comment]
Might've solved it.

**Comment by lyssieth** [comment]
I've solved it, and uninstalled the offending init script + program for now.
