### ISSUE TITLE
rc-status is "crashed"

### ISSUE THREAD

**Issue by DocMAX** [OpenRC/openrc#424]
i don't see what i am doing wrong. the PID is created and points to the the following process:

`/usr/bin/python3.9 /usr/bin/xpra start :14500 --bind-tcp=0.0.0.0:14500 --daemon=yes --pulseaudio=yes --pidfile=/var/run/xpra.pid`

my init:
```
#!/sbin/openrc-run

pidfile="/var/run/xpra.pid"

depend() {
    need net
}

start() {
        ebegin "Starting xpra"
        start-stop-daemon --start --quiet --exec /usr/bin/xpra -- start :14500 --bind-tcp=0.0.0.0:14500 --daemon=yes --pulseaudio=yes --pidfile=/var/run/xpra.pid
        eend $?
}

stop() {
        ebegin "Stopping xpra"
        start-stop-daemon --stop --quiet --pidfile /var/run/xpra.pid
        eend $?
}

```

**Comment by DocMAX** [comment]
I changed one line and it's working now... but is this a bug?
`start-stop-daemon --start --quiet --exec /usr/bin/python3.9 -- /usr/bin/xpra start :14500 --bind-tcp=0.0.0.0:14500 --daemon=yes --pulseaudio=no --pidfile=/var/run/xpra.pid`

**Comment by vapier** [comment]
verify that the pid written to the pidfile matches the actual running process
