### ISSUE TITLE
Login changes from my PC to UNKNOWN

### ISSUE THREAD

**Issue by peepo5** [OpenRC/openrc#426]
When i login, it shows my pc name called PC but it goes straight back to login after i enter. 
It then shows pc name as UNKNOWN.

IS this openrc issue?
using artix.
thanks.

btw logging in second time as unknown works

**Comment by ido** [comment]
This is not the right place for your question.  Please direct your questions to the Artix Linux forums.

**Comment by vapier** [comment]
sounds like a login/auth issue which OpenRC doesn't implement
