### ISSUE TITLE
checkpath -- free(): invalid pointer

### ISSUE THREAD

**Issue by garyemiller** [OpenRC/openrc#459]
I am a long time Gentoo user.  I run Gentoo stable and unstable on a wide range of machines.

On just one, a Gentoo unstable, running on a znver2 CPU, I get this error:

```
# /lib/rc/bin/checkpath -d /tmp/tmp
free(): invalid pointer
Aborted
```

This has persisted for months.  I have done "emerge -e world" many times, with various -mtune, -march, etc. and nothing affects the result.

So I did a "git pull, and looked at src/rc/checkpath.c.  Then make this one change:

```
diff --git a/src/rc/checkpath.c b/src/rc/checkpath.c
index bab22692..df93d7d3 100644
--- a/src/rc/checkpath.c
+++ b/src/rc/checkpath.c
@@ -151,7 +151,8 @@ static char *clean_path(char *path)
        char *ch;
        char *ch2;
        char *str;
-       str = xmalloc(strlen(path));
+       str = xmalloc(strlen(path) + 1);
        ch = path;
        ch2 = str;
        while (true) {
```

The problem goes away.  Looks like xmalloc() is just a wrapper on malloc().

According to "man strlen"

```
       The strlen() function calculates the length of the string pointed to by
       s, excluding the terminating null byte ('\0').
```

Looks to me like "str" is not big enough to hold "path" incuding its trailikng '\0'

No idea how that makes "free(path);" fail.  But I'm glad it does.

.

**Comment by thesamesam** [comment]
... I was just about to look into this because I saw [this](https://bugs.gentoo.org/816900) bug.

Thank you for doing the work!

**Comment by garyemiller** [comment]
Geez, I only had to wait one more day for someone else to do it...
