### ISSUE TITLE
Undo pam pkgconfig change

### ISSUE THREAD

**Issue by thesamesam** [OpenRC/openrc#464]
Only the very latest version of PAM (as of https://github.com/linux-pam/linux-pam/commit/b4f0e2e1f7a18169938eedeff8180e0c75473bb5) ships pkgconfig (.pc) files and so building modern OpenRC isn't going to work on e.g. Ubuntu LTS.

I think we may need to revert bfa634493d48c828330fb2a66418873c3ccf2cb9.

**Comment by vapier** [comment]
doesn't seem like reverting is necessary.  just add find_library fallback logic when pkg-config isn't found.
