### ISSUE TITLE
>=sys-apps/openrc-0.44.7 fails to compile on uclibc toolchain

### ISSUE THREAD

**Issue by stefson** [OpenRC/openrc#471]
hey there, 

=openrc-0.43.5-r1 compiled without any issues, but the upgrade breaks the compile: 

```
armv7a-unknown-linux-uclibceabihf-gcc -Isrc/librc/librc.so.1.p -Isrc/librc -I../openrc-0.44.7/src/librc -I../openrc-0.44.7/src/includes -Isrc/libeinfo -I../openrc-0.44.7/src/libeinfo -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=c99 -D_DEFAULT_SOURCE -Wcast-align -Wcast-qual -Wdeclaration-after-statement -Wformat=2 -Winline -Wmissing-declarations -Wmissing-format-attribute -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wsequence-point -Wshadow -Wwrite-strings -Werror=implicit-function-declaration -O2 -pipe -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=hard -fPIC -MD -MQ src/librc/librc.so.1.p/librc-misc.c.o -MF src/librc/librc.so.1.p/librc-misc.c.o.d -o src/librc/librc.so.1.p/librc-misc.c.o -c ../openrc-0.44.7/src/librc/librc-misc.c
../openrc-0.44.7/src/librc/librc-misc.c: In function 'rc_getfile':
../openrc-0.44.7/src/librc/librc-misc.c:68:7: error: implicit declaration of function 'fileno'; did you mean 'd_fileno'? [-Werror=implicit-function-declaration]
   68 |  fd = fileno(fp);
      |       ^~~~~~
      |       d_fileno
```

```
armv7a-unknown-linux-uclibceabihf-gcc -Isrc/librc/librc.so.1.p -Isrc/librc -I../openrc-0.44.7/src/librc -I../openrc-0.44.7/src/includes -Isrc/libeinfo -I../openrc-0.44.7/src/libeinfo -fdiagnostics-color=always -D_FILE_OFFSET_BITS=64 -Wall -Winvalid-pch -Wextra -Wpedantic -std=c99 -D_DEFAULT_SOURCE -Wcast-align -Wcast-qual -Wdeclaration-after-statement -Wformat=2 -Winline -Wmissing-declarations -Wmissing-format-attribute -Wmissing-noreturn -Wmissing-prototypes -Wnested-externs -Wpointer-arith -Wsequence-point -Wshadow -Wwrite-strings -Werror=implicit-function-declaration -O2 -pipe -march=armv7-a -mfpu=vfpv3-d16 -mfloat-abi=hard -fPIC -MD -MQ src/librc/librc.so.1.p/librc-daemon.c.o -MF src/librc/librc.so.1.p/librc-daemon.c.o.d -o src/librc/librc.so.1.p/librc-daemon.c.o -c ../openrc-0.44.7/src/librc/librc-daemon.c
../openrc-0.44.7/src/librc/librc-daemon.c: In function 'rc_service_daemons_crashed':
../openrc-0.44.7/src/librc/librc-daemon.c:620:9: error: implicit declaration of function 'kill'; did you mean 'killpg'? [-Werror=implicit-function-declaration]
  620 |     if (kill(pid, 0) == -1 && errno == ESRCH)
      |         ^~~~
      |         killpg
```

find the full log here: [build.log.zip](https://github.com/OpenRC/openrc/files/7449374/build.log.zip)
and full emerge --info here: [emerge-info.zip](https://github.com/OpenRC/openrc/files/7449391/emerge-info.zip)

**Comment by williamh** [comment]
Hi,

I imagine that this is because of a header file difference in uclibc, but
I don't have uclibc on my system and it is in the process of being deprecated in Gentoo, so I don't know where I can test.

Any suggestions or patches would be helpful, but be aware that Gentoo is moving away from uclibc so I don't know that I'll have a way to test them.

Thanks,

William

**Comment by williamh** [comment]
Here is the Gentoo newsitem on the subject.
https://www.gentoo.org/support/news-items/2021-08-18-uclibc-ng-retirement.html

Also, I was just informed that as of today the uclibc stages have been removed from the master mirror, so Gentoo officially does not support uclibc new installs.
I highly recommend migrating to musl.

**Comment by stefson** [comment]
hmm, that didn't fix the compile.

**Comment by thesamesam** [comment]
I think you know I'll need a new log then ;)

Was this with master?

**Comment by stefson** [comment]
sure thing, here is the log from current master: [build.log.zip](https://github.com/OpenRC/openrc/files/7532654/build.log.zip)

I used https://github.com/OpenRC/openrc/archive/refs/heads/master.zip to download it, and repacked it as the non-existing openrc-0.44.9 release, simply because the live ebuild died in src_prepare. 

Seems its the same error, the only difference are those offending lines now have an offset of 1 and 2 lines due to your patches.

**Comment by williamh** [comment]
I'll take a look at the live ebuild now, I just saw this comment.
On another note, can you please educate me? Why are you still using uclibc? upstream is dead and it is being removed from Gentoo completely on 2022/1/1. I'm not attempting to start an argument, I just want to understand your reasons.

**Comment by stefson** [comment]
You don't have to look at the live ebuild, its working fine on my amd64 machine. I've actually been unaware of the uclibc removal when I opened this bug, but was using it on a "headless" rpi2, as its super fast.

**Comment by williamh** [comment]
@stefson  Ok, that makes sense, I guess you didn't see the newsitem we sent out. Do you think you'll be able to migrate to musl?
The only reason I can think of that the live ebuild would fail in src_prepare without seeing the log is if you have patches in /etc/portage/patches/openrc on the machine where it failed.

**Comment by thesamesam** [comment]
I'm a bit stumped on the latest failure given kill is defined in signal.h. Probably inclined to say we're not too worried about it unless someone can reproduce with latest uclibc-ng or even better, a supported libc like glibc or musl.
