### ISSUE TITLE
Feature Request: Kernel Module dependencies

### ISSUE THREAD

**Issue by fufik** [OpenRC/openrc#481]
Hello, I 'd like to make to small contribution. The situation was that I needed to use Wireguard VPN and that in turn would want the wireguard module in the kernel. I didn't want to load it on boot, just on the demand, so I came up with this small script in the spirit of /etc/init.d/net.lo from Netifrc called 'mod'
```
#!/sbin/openrc-run
# shellcheck shell=sh disable=SC1008

SHDIR="/lib/netifrc/sh"

# Handy var so we don't have to embed new lines everywhere for array splitting
__IFS="
"

#  Set the INIT to be openrc if this file is called directly
: "${INIT:=openrc}"

if [ -f "$SHDIR/functions.sh" ]; then
	# shellcheck disable=SC1090
	. "$SHDIR/functions.sh"
else
	echo "$SHDIR/functions.sh missing. Exiting"
	exit 1
fi

name="Module loader"
description="Loads a specific module"

#depend() {
#
#}

start() {
	mod_name=$(get_interface)
	modprobe $mod_name
}

stop() {
	mod_name=$(get_interface)
	modprobe -r $mod_name
}

```
And then I do `ln -s /etc/init.d/mod /etc/init.d/mod.wireguard`. Thus I can load modules as services. Now I add the following line into /etc/init.d/wg-quick 
```
need mod.wireguard
```
And voilà, it works. I don't get how to disable it after wg-quick dies, though.

So, my point: I'd like something of that sort in OpenRC in standard distribution, so I could demand specific modules from services.   
And by the way, where can I get the latest documentation on all the features?

**Comment by williamh** [comment]
Here are my comments about Your example

- Avoid using anything from netifrc, so derive mod_name from $RC_SVCNAME.
- It is impossible to stop the `mod.*` service after the service that needs it dies; this does not 
  match how openrc dependencies operate.
- That means kernel module dependencies would only half work.

This feels like a lot of overhead with very little gain. However, I am willing to be convinced otherwise, so let me know what you think.

**Comment by lu-zero** [comment]
If you want to load the module on demand you might use netifrc `preup()` (with the correct configuration, see `up_before_preup` in the documentation)

**Comment by williamh** [comment]
Another thing to consider is whether the kernel could be fixed to load and unload the wireguard module on demand.

I'm going to close this because I don't think there is anything to do in OpenRC, but please feel free to comment and re-open if you think there is.

Thanks much.

William
