### ISSUE TITLE
checkpath tries to fix correct directory mode when using 7000 bits (set*id/sticky)

### ISSUE THREAD

**Issue by lms-jk** [OpenRC/openrc#482]
Hi all, I did not find an obvious issue template so I'm trying to be brief:

I'm using Alpine in an LXC and set up a custom service for the default runlevel. checkpath in start_pre() tries to fix the mode of a directory that is already set correctly. This happens every time.

"error" message:
``` text
 * Executing: /lib/rc/sh/openrc-run.sh /lib/rc/sh/openrc-run.sh /root/services/open-rc/init.d/docker-jenkins start
 * /home/jenkins: correcting mode
 ...
```
corresponding line in start_pre():
```
checkpath --directory --mode 2755 --owner jenkins:jenkins /home/jenkins
```
the directory:
```
# ls -l /home
drwxr-sr-x   16 jenkins  jenkins       4096 Dec  9 14:33 jenkins
```
It is not harmful, but this is not the expected behavior. Let me know if i can provide more data.

**Comment by vapier** [comment]
thx for the detailed report
