### ISSUE TITLE
polkit service issue

### ISSUE THREAD

**Issue by CountOmega** [OpenRC/openrc#485]
I'm running debian with openrc and xfce4. I wrote a service script for polkit like this:

```
#!/sbin/openrc-run
# Copyright 2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

name="Authorization manager"
description="a service for managing authorizations"
command="/usr/libexec/polkitd"
command_args="${ --no-debug}"


depend() {
	after dbus
	after elogind
}
```
But it isn't working properly so far. What am I missing here?

**Comment by E5ten** [comment]
I'm not sure what/ you want it to expand to, but `${ --no-debug}` is not a valid variable or expansion, so maybe the shell is erroring there?

**Comment by CountOmega** [comment]
Yeah that was the issue. Still the service isn't running as expected. The systemd service file connects to dbus:
```
[Unit]
Description=Authorization Manager
Documentation=man:polkit(8)

[Service]
Type=dbus
BusName=org.freedesktop.PolicyKit1
ExecStart=/usr/libexec/polkitd --no-debug

```
How can I do this in OpenRC?

**Comment by E5ten** [comment]
I think more detail about what you mean by not running as expected is probably needed, e.g. is it erroring, is the service successfully running but not having the intended effects or something, etc.?

**Comment by cromerc** [comment]
As far as I am aware, pokit is a user service, not a system service. It is meant to be run when the user logs into a graphical session. Most DEs launch polkit either through XDG or dbus activation. I have never heard of or seen someone trying to run it as a system service.

**Comment by E5ten** [comment]
After looking a bit further, I think an issue may be that polkitd (I'm guessing) runs in the foreground, while start-stop-daemon needs it to run in the background, or have `command_background=true` set to background it itself? Looking at the service script Alpine uses for it, they have `supervisor=supervise-daemon`, which unlike start-stop-daemon, needs its command to run in the foreground. Try adding that to the file.

**Comment by CountOmega** [comment]
Thanks for all the helpful replies. The following is working for me:

```
#!/sbin/openrc-run
# Copyright 2021 Gentoo Authors
# Distributed under the terms of the GNU General Public License v2

name="PolicyKit daemon"
description="a service for managing authorizations"
pidfile="/var/run/polkitd/polkitd.pid"
command="/usr/libexec/polkitd"
command_args="--no-debug"


depend() 
{
    need dbus
}

```
