### ISSUE TITLE
netmount: glusterfs not automatically unmounted with new "fuse.glusterfs" name

### ISSUE THREAD

**Issue by tusooa** [OpenRC/openrc#495]
rc.conf says:
```
# Below is the default list of network fstypes.
#
# afs ceph cifs coda davfs fuse fuse.sshfs gfs glusterfs lustre ncpfs
# nfs nfs4 ocfs2 shfs smbfs
```

But the fs type for glusterfs is now `fuse.glusterfs` (as of Gentoo's `sys-cluster/glusterfs-10.0`).

Setting `extra_net_fs_list="fuse.glusterfs"` works, but I guess we should add that also to default net fstypes.

**Comment by vapier** [comment]
easy enough to add, although i'll note that you should be adding `_netdev` to all such mounts in the first place.  if you did, it'd get automatically unmounted.
