### ISSUE TITLE
New Release 0.44.11?

### ISSUE THREAD

**Issue by LinkTed** [OpenRC/openrc#501]
It would be nice to release a new version. Because it would contain the capabilities support 6e214b261604c4ab1ffc244272443a587bb59927 and other security features.

**Comment by genbtc** [comment]
I would enjoy a new 0.44.11 release for the seedrng entropy fixes, please?
bump.

**Comment by jirutka** [comment]
As an Alpine Linux developer, I’m also eagerly awaiting the new release with the capabilities support.

**Comment by LinkTed** [comment]
Thanks
