### ISSUE TITLE
question: prevent service from beeing stopped at shutdown

### ISSUE THREAD

**Issue by mrl5** [OpenRC/openrc#534]
is it possible to prevent openrc from stopping service when it goes to shutdown level?

my usecase is that I'm trying to create an init script that should be started at boot and should not be stopped (esp. at shutdown) unless it's the user that explicitly triggered `/etc/init.d/my-service stop`

**Comment by mrl5** [comment]
I found a solution:
```bash
stop() {
	# man 8 init
	# Runlevel 0 is used to halt the system;
	# runlevel 6 is used to reboot the system.
	if [[ $($runlevel_command) =~ (0|6)$ ]]; then
		ebegin "Stopping \"lkrg\" service without unloading \"p_lkrg\" module from the kernel"
		eend $?
	else
		ebegin "Unloading \"p_lkrg\" module from the kernel"
		$command $unload_command_args
		eend $?
	fi
}
```

in case someone is interested in context: https://github.com/lkrg-org/lkrg/pull/197#issuecomment-1175588110

**Comment by vapier** [comment]
you could put your service into `/etc/runlevels/shutdown/`, although that would mean it starts up too
