### ISSUE TITLE
Wrong permissions github wiki

### ISSUE THREAD

**Issue by AltF02** [OpenRC/openrc#538]
So I was messing around and I think anyone can just make wiki pages. Possibly something you'd want to fix?

**Comment by vapier** [comment]
ask for forgiveness, not for permission!

**Comment by williamh** [comment]
For now, i can disable the wiki unless someone wants it.
The official docs are in the distribution, so I don't think we need the wiki.
Please open a discussion if you disagree.

**Comment by vapier** [comment]
wiki's are lower overhead and allow for many more examples/snippets/thoughts than typically make sense in curated official docs
