### ISSUE TITLE
Via `shutdown`/`reboot`, provide the ability to easily access the (U)EFI.

### ISSUE THREAD

**Issue by RokeJulianLockhart** [OpenRC/openrc#539]
1.	#### **Examples of Current Implementations**
	
	1.	The *Windows* family of OSes all provide `shutdown /r /fw /f /t 0` to perform this, per https://github.com/JakeTurner616/reboot-to-uefi/blob/3f9ad9b4dfb5e1dfb13a2d26157ab1ac5d2f76bc/reboot-to-bios.bat#L6.
	1.	The *SystemD* initialization system provides `systemctl reboot --firmware-setup` for Linux, per https://www.reddit.com/r/linuxmasterrace/comments/ltg8j7/i_just_use_sudo_systemctl_reboot_firmwaresetup/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button, and
	1.	`efibootmgf -f` is available for BSD, per https://www.reddit.com/r/freebsd/comments/u26tx6/comment/i4h0tnb/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button.
	1.	If what I've posted at https://developer.apple.com/forums/thread/711532?answerId=725918022 is correct, even macOS supports this to an extent.
	
1.	#### **Current Status of Feature**
	
	Consequently, for shims such as https://github.com/adoakley/efi-boot-to-fw-ui/blob/ae670d6080323625ca928838560c0e7ab7d027d9/README.md?plain=1#L4 to be necessary when utilizing `openrc` disappoints me. I am unable to recommend some distributions merely because this feature is absent, and this is especially problematic for PMOS, because absence of this feature means that no decent replacement to `adb reboot bootloader` exists.
	
	I am thankful for any assistance.

**Comment by vapier** [comment]
are you using OpenRC's init, or sysvinit ?

**Comment by rokejulianlockhart** [comment]
@vapier, I was using whatever PostmarketOS uses. I don't know what that is. I don't have a device with it installed currently to ascertain it.

Do you want me to create a VM and try to ascertain which, or would you rather? I don't know what exactly to search for after configuring the VM.

**Comment by vapier** [comment]
no need to reinstall.  my point is that if they're using sysvinit, you'd have to put in a request with that project instead.  if they're using OpenRC's bundled init, then it's something we can look at.

**Comment by rokejulianlockhart** [comment]
@vapier, per https://matrix.to/#/!zpvMifoucHSiUsVFgl:postmarketos.org/$OKfh4lqbxgTGraKh4obtPPhzV6PZWdIaoe7ng0Sh-6k?via=matrix.org&via=kde.org&via=tchncs.de, always OpenRC. I trust Newbyte and the official wiki enough to state this in confidence.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/OpenRC/openrc/issues/539#issuecomment-1453572722

@Newbytee, I've been waiting a while for a response...

**Comment by Newbytee** [comment]
> In which case, @Newbytee, should this be reported to https://bugs.busybox.net/enter_bug.cgi?product=Busybox&component=Standard%20Compliance?

The answer is that I'm not 100% sure.

**Comment by RokeJulianLockhart** [comment]
> https://github.com/OpenRC/openrc/issues/539#issuecomment-1986845118

https://xdaforums.com/t/what-initialization-system-does-postmarketos-use.4660936/post-89389406

**Comment by RokeJulianLockhart** [comment]
> https://github.com/OpenRC/openrc/issues/539#issuecomment-1986852664

https://wiki.postmarketos.org/index.php?title=Boot_process&oldid=47210#Overview:~:text=postmarketOS%20initramfs-,openrc,-LightDM%20(if%20UI states https://wiki.postmarketos.org/index.php?title=OpenRC&oldid=42949#:~:text=it%20is%20the%20default%20system%20in%20postmarketos - that it is currently OpenRC.

**Comment by RokeJulianLockhart** [comment]
Paraphrased, [this Reddit comment](https://www.reddit.com/r/artixlinux/comments/k5nq5c/comment/lb9kg0f/?utm_source=share&utm_medium=web3x&utm_name=web3xcss&utm_term=1&utm_content=share_button) explains that the command is:

<blockQuote>

I was going to tell the guy about that. However, I don't have an account on GitHub after losing my 2FA credentials. In OpenRC, this is how you'd run it, because OpenRC uses `elogind`:

```sh
loginctl reboot --firmware-setup
```

</blockQuote>

so I shall close this issue as invalid, for it appears possible, and is outside the remit of this issue (due to using `loginctl`, rather than the requested `reboot` and/or `shutdown`). If I am incorrect, please inform me - I can't test the command myself anymore.
