### ISSUE TITLE
hwclock init script logging grep warning

### ISSUE THREAD

**Issue by particleflux** [OpenRC/openrc#548]
With the latest `grep` (3.8), the `hwclock` init script throws a warning on start in the logic to detect `--noadjfile` argument support:

https://github.com/OpenRC/openrc/blob/112b69860f2cb6059c49404abbfb4e3f22603cfc/init.d/hwclock.in#L74-L75

```
hwclock                   | * Setting system clock using the hardware clock [UTC] ...
hwclock                   |grep: warning: stray \ before -
hwclock                   |grep: warning: stray \ before -
```

This seems to have been introduced in `grep` in this commit: https://git.savannah.gnu.org/cgit/grep.git/commit/?id=e7f8e8eb1fd41b308ee10741bbd8068acc1847c2

I think replacing the affected logic with 

```
grep -q -- "--noadjfile"
```

should work.

**Comment by vapier** [comment]
normally we'd use `-e` instead of `--` for portability.  want to send a PR for that ?

**Comment by particleflux** [comment]
Oh, sure, `-e` makes more sense anyway.

I'll create a PR
