### ISSUE TITLE
Unmatched ebegin "Mounting /run" in linux init.sh

### ISSUE THREAD

**Issue by nbuwe** [OpenRC/openrc#554]
https://github.com/OpenRC/openrc/blob/9380347f042f7d294317f4420b648422817eb75a/sh/init.sh.Linux.in#L73
That `ebegin` doesn't have a matching `eend` at the the end of the `if`.  That causes spurious blank line in the output and no "ok" status:
```
 * Mounting /run ...
 * /run/openrc: creating directory

 * /run/lock: creating directory
 * /run/lock: correcting owner
```
Cf. the correct code in the GNU version:
https://github.com/OpenRC/openrc/blob/9380347f042f7d294317f4420b648422817eb75a/sh/init.sh.GNU.in#L32

With the `eend` added the output is
```
 * Mounting /run ... [ ok ]
 * /run/openrc: creating directory
 * /run/lock: creating directory
 * /run/lock: correcting owner
```

**Comment by vapier** [comment]
thx for the report
