### ISSUE TITLE
configure shutdown broadcast message

### ISSUE THREAD

**Issue by lever1209** [OpenRC/openrc#555]
i have a system that takes a while to shutdown because of certain services, and it would be nice to change the message to something more appropriate
"System will reboot now" doesnt make too much sense if it will be another 5-10 minutes before the system completely shuts down

maybe put it in `/etc/rc.conf`?

**Comment by vapier** [comment]
if services are shutting down, then the system is rebooting. that is defined not only in terms of the kernel, but also the userland init state. so the current behavior sounds correct to me.

**Comment by vapier** [comment]
afaik, OpenRC & sysvinit present the same messaging (more or less), and have so for decades.  i don't think the current behavior is incorrect.  if you can point to sysvinit behaving differently, feel free to re-open for us to re-evaluate.
