### ISSUE TITLE
Please document that init scripts need to run with no arguments

### ISSUE THREAD

**Issue by samboy** [OpenRC/openrc#561]
This may be obvious, but for those of us porting init scripts to OpenRC, please document the following:

If an init script in `/etc/init.d` fails when run with no arguments, the service in question will not be started at system boot. This is because OpenRC runs `/etc/init.d` scripts without arguments to find out their dependencies.

(You may add this sentence to any relevant documentation)

It took me nearly two hours to find out why my old RedHat `/etc/init.d` scripts were not running at system boot time in Alpine Linux.

**Comment by vapier** [comment]
you shouldn't be dropping arbitrary shell scripts into /etc/init.d.  you should only be putting openrc scripts in there.

**Comment by samboy** [comment]
That mostly works. For the lurkers:

* For `/etc/local.d` scripts to run, they need to have a name like `/etc/local.d/foo.start` for starting a service, and `/etc/local.d/foo.stop` for stopping a service
* There’s a special OpenRC service called local which needs to be enabled: `rc-update add local`
* Since the start and stop scripts are separate, they work best as wrappers to `sysvinit` scripts, e.g. for `foo.start`

```sh
#!/bin/sh
/usr/lib/foo/init/foo start
```

Which calls the `sysvinit` script `/usr/lib/foo/init/foo` with the `start` argument, the way a `sysvinit` script (or, likewise, a scripted called by `systemd` via the `systemd-sysv-generator` helper) is usually called.

Now, a rant: There really needs to be some kind of standardization of how to start services across Linux and BSD distributions the way POSIX standardized all of the SunOS-vs-IRIX-vs-AIX nonsense we had in the 1990s. It’s unfortunate that `sysvinit` didn’t become part of the POSIX standard. 

Right now, `sysvinit` (and `systemd` which is compatible with that) have one way of starting services, OpenRC has another way of starting services, [s6](https://skarnet.org/software/s6/) probably has another way, as well as [daemontools](https://cr.yp.to/daemontools.html) (which is much older than `systemd`), [daemontools-encore](https://untroubled.org/daemontools-encore/), [runit](http://smarden.org/runit/), [perp](http://b0llix.net/perp/), [nosh](http://jdebp.uk./Softwares/nosh/), [minit](https://www.fefe.de/minit/), [sinit](https://git.suckless.org/sinit/), [Upstart](https://upstart.ubuntu.com/), and so on. 

As you can imagine, if each and every single one of these init systems has their own special file configuration format which needs to be used to start a service at system boot time, that might be a little too much to ask various free software projects to support them, especially since there isn’t any money on the table. That’s why I have put the foot down and will only support `systemd` (which covers 90% or more of Linux systems) but welcome pull requests if people want support for other init systems. Since, right now the only third party package being updated is one for Fedora (systemd), that covers my active users (there used to be Debian, FreeBSD, and other packages, but they haven’t been updated in a while).

OK, enough of the rant. Let me open up another ticket asking for an `/etc/rc.local` file (another old informal standard which `systemd` alas doesn’t support).

**Comment by samboy** [comment]
I should probably clarify https://github.com/samboy/MaraDNS/commit/85d475406931bbdd423adc9fbdef83ed2bc084f5 here

I have no problem with OpenRC *per se*. But, I don’t have time to add support myself. **However**, I will happily accept a pull request which adds OpenRC support to MaraDNS.

**Comment by vapier** [comment]
only providing systemd unit files sounds reasonable
