### ISSUE TITLE
What are duplicate services?

### ISSUE THREAD

**Issue by gagero** [OpenRC/openrc#566]
Ocassionally, when I try to start display-manager (provided through `gui-libs/display-manager-init` on Gentoo) or add it to the default runlevel, I get the error "display-manager is the name of a real and virtual service.". In `src/librc/librc-depend.c`, there's a comment indicating that this warns of a duplicate service. What is a duplicate service and can I somehow "deduplicate" it?

**Comment by vapier** [comment]
look in /etc/init.d/ for scripts that `provide display-manager`.  those are virtual ones.

then look for scripts literally named `display-manager.conf`.  those are real ones.

you shouldn't mix the two.
