### ISSUE TITLE
Unify issue trackers: GH vs bugs.g.o

### ISSUE THREAD

**Issue by tiziodcaio** [OpenRC/openrc#576]
I've seen we have a bugzilla for openrc and the github issues here... Should we unify the issue form? Where should I report an issue?

**Comment by vapier** [comment]
the README seems pretty clear:
> `Please report bugs on our [bug tracker](http://github.com/OpenRC/openrc/issues).`

**Comment by vapier** [comment]
*shrug* i don't think it's a big deal tbh
