### ISSUE TITLE
tmpfiles.sh : doesn't support tmpfiles.d   v option

### ISSUE THREAD

**Issue by LW-archlinux** [OpenRC/openrc#59]
tmpfiles: ignoring invalid entry on line 11 of `/usr/lib/tmpfiles.d//tmp.conf'
tmpfiles: ignoring invalid entry on line 12 of `/usr/lib/tmpfiles.d//tmp.conf'
tmpfiles: ignoring invalid entry on line 21 of `/usr/lib/tmpfiles.d//var.conf'

these are the 3 lines that gives this message : 
v /tmp 1777 root root 10d
v /var/tmp 1777 root root 30d
v /var/lib/machines 0700 - - -

from man timpfiles.d :
      v
           Create a subvolume if the path does not exist yet and the file system supports this (btrfs). Otherwise  create a normal directory, in the same way as d.

Note : archlinux, booting openrc 0.16.4 with systemd 219 (used for udev)

**Comment by dwfreed** [comment]
This has since been fixed
