### ISSUE TITLE
question regarding defaulting to unicode=YES

### ISSUE THREAD

**Issue by nekopsykose** [OpenRC/openrc#607]
i recently noticed that when setting a default LANG that ends with `UTF-8`, things in the console that output special characters (pipes, bars, ..) appear broken if the console is not also set to utf-8. the console setting for this is set via the default-shipped termencoding service, reading the UNICODE value.

the default for it is not-unicode, from the default rc.conf https://github.com/OpenRC/openrc/blob/95b2948e6e153271249b09b9b1505c527c54e0cd/etc/rc.conf#L92  

is there:

- potential downsides to defaulting to 'YES' distro-wide
- a reason it's not the default already?

**Comment by vapier** [comment]
we should change the default at this point
