### ISSUE TITLE
net-misc/netifrc-0.7.3-r1 issue with net-misc/dhcpcd-10.0.0

### ISSUE THREAD

**Issue by baconsalad** [OpenRC/openrc#620]
Just installed dhcpcd-10.0.0 and after rebooting net.eth0 failed with
```
# /etc/init.d/net.eth0 restart
 * Bringing up interface eth0
 *   Caching network module dependencies
 *   dhcp ...
 *     The dhcpcd version is too old. Please upgrade.                               [ !! ]
 * ERROR: net.eth0 failed to start
```

/lib/netifrc/net/dhcpcd.sh regex needs an update.

**Comment by thesamesam** [comment]
This is an issue in the netifrc package so should be reported in Gentoo.

**Comment by baconsalad** [comment]
Sorry, followed some links and ended up here. I'll post over there.

**Comment by thesamesam** [comment]
No worries - handled at https://bugs.gentoo.org/904422.
