### ISSUE TITLE
completion scripts unset extglob, breaking bash-completion

### ISSUE THREAD

**Issue by jjakob** [OpenRC/openrc#636]
```
gentoo ~ # rc-service sshd status
 * status: started
gentoo ~ # vim /e-bash: syntax error near unexpected token `('
tc/^C
gentoo ~ # ^C
```

Offending line
https://github.com/OpenRC/openrc/blob/92662ddc44f6091e8085fcd4637d13f04e90c5ac/bash-completion/rc-service#L101

From discussion in #bash on libera.chat "all completion scripts can reasonbly expect that extglob has been enabled in advance"

Related discussion on extglob in bash completion scripts:
https://bugs.gentoo.org/267788

**Comment by jjakob** [comment]
It's also not needed for the glob that extglob is being set for
https://github.com/OpenRC/openrc/blob/92662ddc44f6091e8085fcd4637d13f04e90c5ac/bash-completion/rc-service#L97
The pattern to the right of `==` in `[[` is always matched as if extglob were enabled, so setting it is not necessary

**Comment by thesamesam** [comment]
See also https://github.com/OpenRC/openrc/issues/344#issuecomment-1412148373.
