### ISSUE TITLE
unable access keyboard and mouse

### ISSUE THREAD

**Issue by end3r-man** [OpenRC/openrc#683]
New to openrc my startup fine able to get into login manager but unable to access keyboard and mouse but NumLock on mouse also arch Linux

**Comment by end3r-man** [comment]
Tried other login manager like lightdm, tbsm, sddm, gnome login manager

**Comment by vapier** [comment]
if you've spawned a GUI session manager and can see it, then openrc is working. drivers not working is rarely the purview of openrc. you probably want to ask on your distro forums for help instead.

**Comment by end3r-man** [comment]
That's the problem after installing openrc I'm unable to login into my wm tty also
