### ISSUE TITLE
Trying to build OpenRC as static

### ISSUE THREAD

**Issue by redat00** [OpenRC/openrc#687]
Hey there! 

I'm trying to build OpenRC for a small Linux environment I'm building from scratch. I was wondering if maybe it was possible to build OpenRC binaries as static, and thus preventing the need for me to have to also build all the required libraries ? 

Already tried with the `meson setup buildingdir --default-library static` option, which seem to have effect, but not as much as I wanted (still requires libc6 for example). 

With the `--default-library static` option
```
ldd buildir/src/openrc/openrc
	linux-vdso.so.1 (0x00007ffefe8e1000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fcfbde00000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fcfbe25c000)
```

Without the option
```
ldd buildir/src/openrc/openrc
	linux-vdso.so.1 (0x00007ffc9acd6000)
	libeinfo.so.1 => /home/redat/Documents/linuxscratch/src/openrc-0.53/buildir/src/openrc/../libeinfo/libeinfo.so.1 (0x00007fb73bff7000)
	librc.so.1 => /home/redat/Documents/linuxscratch/src/openrc-0.53/buildir/src/openrc/../librc/librc.so.1 (0x00007fb73bfe3000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007fb73bc00000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb73c013000)
```

I'm new to `meson`, and since the `README.md` just tell me `use the usual methods for this build system to build and install`, the command I'm using are the one I was able to find on the internet. I might be using the wrong ones.

If anyone can point me in the correct direction (maybe to a more complete `How to build openrc` documentation) ! 

Otherwise, a list of the required libraries would be nice too. If anyone knows how I can find it, I would be able to build them. 

Thanks in advance for any help !

**Comment by eli-schwartz** [comment]
> I was wondering if maybe it was possible to build OpenRC binaries as static, and thus preventing the need for me to have to also build all the required libraries ?
> 
> Already tried with the `meson setup buildingdir --default-library static` option, which seem to have effect, but not as much as I wanted (still requires libc6 for example).

This option tells meson to build openrc with all of openrc's libraries created as static libraries.

As for other required libraries, all there is left is really just libc? You can pass compiler flags into $CFLAGS, such as `-static`, to force it to build fully static binaries.
