### ISSUE TITLE
failed to commit transaction (conflicting files) - update openrc  0.53-1 -> 0.54-1

### ISSUE THREAD

**Issue by LuisBorges7** [OpenRC/openrc#703]
==> Sources are ready.
loading packages...
resolving dependencies...
looking for conflicting packages...

Packages (1) openrc-0.54-1

Total Installed Size:  1,45 MiB
Net Upgrade Size:      0,00 MiB

:: Proceed with installation? [Y/n] y
(1/1) checking keys in keyring                                                                                    [####################################################################] 100%
(1/1) checking package integrity                                                                                  [####################################################################] 100%
(1/1) loading package files                                                                                       [####################################################################] 100%
(1/1) checking for file conflicts                                                                                 [####################################################################] 100%
error: failed to commit transaction (conflicting files)
openrc: /bin exists in filesystem (owned by filesystem)
openrc: /lib exists in filesystem (owned by filesystem)
Errors occurred, no packages were upgraded.
 -> error installing: [/home/user1/.cache/yay/openrc/openrc-0.54-1-x86_64.pkg.tar.zst] - exit status 1

**Comment by Duter2016** [comment]
I had the same problem with Arch Linux.

**Comment by thesamesam** [comment]
Please report this to your packaging provider.

**Comment by navi-desu** [comment]
this is a packaging issue, as sam mentioned, please report to the downstream package maintainer.
