### ISSUE TITLE
[0.20] [cryptsetup] services between luks prompt and login do not show

### ISSUE THREAD

**Issue by r1k0** [OpenRC/openrc#73]
![img_3744](https://cloud.githubusercontent.com/assets/238676/12306092/59ee2694-ba38-11e5-9ab4-4f8cbc2e775c.JPG)

0.19.1 works fine. I'm running gentoo full unstable.

Let me know if you need more info.

**Comment by dwfreed** [comment]
Are you sure they're not running, versus not printing to the console?  The output of rc-status -a and the contents of /etc/inittab would be helpful.

**Comment by dwfreed** [comment]
Something tells me your issue is fixed by d4c7207; could you try openrc-9999?

**Comment by r1k0** [comment]
Thank you for having a look.
I will try later on today and report back.

**Comment by r1k0** [comment]
0.20.1 indeed solves the issue.
Thank you
