### ISSUE TITLE
Problems with 0.20.1 make in chroot

### ISSUE THREAD

**Issue by udeved** [OpenRC/openrc#74]
Hi,

I run into a strange problem with latest version 0.20.1, I have trouble compiling it, but only in chroot.

If I use makepkg, ie build host is running system, everything goes well, the package gets created.

If I try to make the package in chroot, same build as for 0.19.1, it fails:

log:
http://pastebin.com/jcFtaULy

   $ uname -a
    Linux manjaro-openrc 4.2.8.1-1-MANJARO #1 SMP PREEMPT Fri Jan 8 23:56:16 UTC 2016 x86_64  GNU/Linux

Is there a new depend I am missing?

**Comment by williamh** [comment]
Hello,

can you please test with 0.20.2 and let me know if you still see this?

Thanks,

William

**Comment by udeved** [comment]
Thanks a lot, 0.20.2 builds fine in chroot. :)

~~~
==> Tidying install...
  -> Purging unwanted files...
  -> Removing libtool files...
  -> Removing static library files...
  -> Compressing man and info pages...
  -> Stripping unneeded symbols from binaries and libraries...
==> Creating package "openrc"...
  -> Generating .PKGINFO file...
  -> Adding install file...
  -> Generating .MTREE file...
  -> Compressing package...
==> Leaving fakeroot environment.
==> Finished making: openrc 0.20.2-1 (Thu Jan 14 20:15:40 UTC 2016)
==> Signing package '/build/manjaro-tools/pkg/unstable/x86_64/openrc-0.20.2-1-x86_64.pkg.tar.xz' with key ...
==> Finished building [openrc]
 --> Time make_pkg: 0.78 minutes
~~~

**Comment by williamh** [comment]
Ok, thanks for testing. :-)
