### ISSUE TITLE
How do you define supervise-daemon arguments in an OpenRC script?

### ISSUE THREAD

**Issue by andar1an** [OpenRC/openrc#761]
I am working on converting some services to use supervise-daemon, however, in some circumstances s-s-d arguments exist. 

e.g. `start_stop_daemon_args="-g wheel -k 027"`

How can I define similar arguments for the supervise-daemon? 

I see that the flags exist, but I am not sure how to pass them to the supervisor. I have tried a few different ways, and it seems my service just keeps reloading so I don't believe it is working.

**Comment by andar1an** [comment]
seems that it is still "start_stop_daemon_args" which is very confusing.

**Comment by navi-desu** [comment]
it's `supervise_daemon_args`, which (for some reason?) falls back to `start_daemon_args` if it's unset

**Comment by andar1an** [comment]
Thanks, I see that now. I have been using s-s-d args, but will switch now.

**Comment by andar1an** [comment]
May be busybox acpid appearing not to have foreground arg now, but it worked before which is weird

**Comment by navi-desu** [comment]
docs say `-f` is foreground, i'd recommend testing in a shell to see if it's staying on the foreground properly, and if so, run rc-service with the -d (or --debug) flags to see what openrc is doing wrong

**Comment by andar1an** [comment]
For some reason it is stating that the wheel group does not exist now, which it does, and I wasn't getting this error before. I will need to figure out what changed.

**Comment by navi-desu** [comment]
unless something else changes by checking RC_DEBUG, nop

all it does is enable `set -x` on the shell running openrc

**Comment by andar1an** [comment]
What is the default group that supervise-daemon runs under? `daemon`?

**Comment by andar1an** [comment]
Seems log is spitting out:
```
acpid: LID/00000080
acpid: LID/00000080: No such file or directory
```

**Comment by navi-desu** [comment]
> What is the default group that supervise-daemon runs under? `daemon`?

unless you pass in `-g`, root:root

**Comment by andar1an** [comment]
Ya, it seems the acpid socket is mussing, dk why yet.

**Comment by andar1an** [comment]
Gonna close this now. It is clearly something to do with ACPID at this point, and not arguments. Thanks for the info.

**Comment by andar1an** [comment]
As an update if curious, I believe busybox acpid is supposed to have standard config for power buttons and lib, but seems that is missing for me. Unrelated to supervise daemon, but maybe it is time for clean install lol.
