### ISSUE TITLE
cgroup v2 support

### ISSUE THREAD

**Issue by Ferroin** [OpenRC/openrc#94]
Version 2 of cgroups has been considered stable in the mainline kernel for two release cycles now.  It would be really nice to have the option to use it with OpenRC.

Based on my (limited) knowledge of the internals of cgroupv2 and OpenRC, here's what would have to change:
- Add an option in rc.conf to select between cgroup v1 and cgroup v2 support.
- Abstract how paths are constructed to files in cgroups.  cgroup v2 uses a unified hierarchy (equivalent to everything being co-mounted), usually rooted at /sys/fs/cgroup.
- Add a config option to select which controllers to enable when using cgroup v2.  cgroup v2 requires controllers to be explicitly enabled before they can be used.
- Add a config option to specify parameters for cgroup v2 controllers.  Because of the unified hierarchy, it makes little sense to split the config for each controller to a separate variable.

**Comment by williamh** [comment]
Yes, I am interested in supporting this, and will start working on it soon.

**Comment by stalkerg** [comment]
Can you say about current status?

**Comment by williamh** [comment]
Cgroups v2 wasn't actually considered stable upstream until linux-4.13 which has just been released today, so I will begin working on it.

Does anyone have any suggestions about whether I should keep cgroups v1 around and how to do that?The cgroups v1 code is buggy due to race conditions which I haven't been able to reproduce, much less solve, , so the sooner I could move completely away from cgroups v1 the better.

**Comment by Ferroin** [comment]
I would say you should absolutely keep cgroup v1 support around despite the bugs, there are things you can't do in cgroup v2 but can in cgroup v1 (they decided to ignore some of the  primary use cases in designing cgroup v2, so there are a number of people who are or will be stuck on v1 for at least the foreseeable future).

From my perspective, I would think the cleanest way to do the cgroup v2 stuff from scratch, then use whatever variable is used to select v1 or v2 to select the implementation too.  There might be some shareable code, but I don't think any of that reasonably shareable code is likely to be where the race conditions are.
