### ISSUE TITLE
modules-load.d support can cause kernel modules to be loaded twice

### ISSUE THREAD

**Issue by amak79** [OpenRC/openrc#98]
On my Gentoo system the `app-emulation/virtualbox-modules` package installs `/usr/lib/modules-load.d/virtualbox.conf` for systemd users. However I use OpenRC, and I specify the VirtualBox kernel modules in `/etc/conf.d/modules`. The modules-load.d support that was added to 0.21.x with commit 556dbff99d, will cause the VirtualBox kernel modules to be loaded twice during boot. Is there any way to prevent the modules listed in `/usr/lib/modules-load.d` from being loaded?

**Comment by dwfreed** [comment]
Make an empty `/etc/modules-load.d/virtualbox`, or symlink that path to `/dev/null`
